### PR TITLE
[ESIMD] host device disabled for ESIMD kernels

### PR DESCRIPTION
**Pull request by dongkyunahn-intel**
- esimd_media_block_load/store intrinsic implementation for host
device is changed to use ESIMD_CPU plug-in in intel/llvm PR#4020

- The implementation is not compatible with host device mode therefore
tests calling impacted intrinsics must be marked UNSUPPORTED for host
device

### CODE REVIEW

**Comment by v-klochkov** [comment]
The only failed test - slm_gather_scatter_rgba.cpp. It has been fixed yesterday. This PR would need rebase or git-merge.

**Comment by dongkyunahn-intel** [comment]
Will merge after https://github.com/intel/llvm-test-suite/pull/505.

**Comment by kbobrovs** [comment]
Per our discussion, let's not disable HOST_RUN for this tests at this point and follow these steps:
- split the compiler's 4020 into two parts - __esimd* implementation based on CM lib and the rest (PI ESIMD EMU plugin)
- merge the latter PR (plugin part) and enable it by default
- have vadd_1d HOST_RUN_PLACEHOLDER replaced with ESIMD_EMU_RUN_PLACEHOLDER, and it should pass with the EMU plugin
- over time, convert HOST_RUN_PLACEHOLDER to ESIMD_EMU_RUN_PLACEHOLDER in other ESIMD tests, in accordance with  intrinsics emulation implementation readiness

**Comment by dongkyunahn-intel** [comment]
Closing as planning for transition to `ESIMD_EMU_RUN_PLACEHOLDER` is changed.

**Pull request closed without merging**
