### PR TITLE
[SYCL] Rename ROCm plugin to HIP

### PR DESCRIPTION
**Pull request by npmiller**
This patch matches the changes in:

* https://github.com/intel/llvm/pull/4418

~~It also currently includes the changes from:~~
* ~~#425 ~~

~~This is to avoid conflicts and so that the testing can be run on AMD.~~

~~I suggest we try to merge #425 first and then I can rebase this PR (or we could close #425 and merge it with this one).~~

### CODE REVIEW

**Review by bader — DISMISSED** [review]

**Review by vladimirlaz — DISMISSED** [review]

**Review by Fznamznon — DISMISSED** [review]

**Comment by npmiller** [comment]
Rebased now that #425 was merged.

**Review by vladimirlaz — DISMISSED** [review]

**Review by AlexeySachkov — DISMISSED** [review]

**Review by AGindinson — DISMISSED** [review]

**Comment by npmiller** [comment]
Rebased and updated to also change the `on-device` tests that were recently moved from the main repo

**Review by AGindinson — DISMISSED** [review]

**Review by kbobrovs — DISMISSED** [review]
ESIMD tests LGTM

**Comment by bader** [comment]
@npmiller, please, resolve merge conflicts.

**Comment by npmiller** [comment]
> @npmiller, please, resolve merge conflicts.

Rebased and conflicts resolved

**Review by bader — APPROVED** [review]

**Review by vladimirlaz — APPROVED** [review]

**Review by AGindinson — APPROVED** [review]

**Review by sergey-semenov — APPROVED** [review]

**Pull request merged**
