### PR TITLE
[SYCL] Use int instead of pi_mem_advice in mem_advise

### PR DESCRIPTION
**Pull request by dnmokhov**
Passes with intel/llvm#4100.

### CODE REVIEW

**Review by s-kanaev — APPROVED** [review]
LGTM

**Review by vladimirlaz — APPROVED** [review]

**Comment by vladimirlaz** [comment]
need to wait till nightly from July 15 to restart tests

**Comment by dnmokhov** [comment]
Can this be merged now that the all the checks have passed?

**Comment by romanovvlad** [comment]
@jbrodman Could you please review?

**Pull request merged**
