### PR TITLE
[SYCL] Add support for device_read_only shared USM allocations

### PR DESCRIPTION
**Pull request by smaslov-intel**
E2E test for https://github.com/intel/llvm/pull/5832
Signed-off-by: Sergey V Maslov <sergey.v.maslov@intel.com>

### CODE REVIEW

**Comment by smaslov-intel** [comment]
The failed test is expected and is passed with https://github.com/intel/llvm/pull/5832:
>Failed Tests (1):
[2022-03-21T08:56:32.825Z]   SYCL :: Plugin/level_zero_usm_device_read_only.cpp

**Comment by smaslov-intel** [comment]
ping

**Review by rdeodhar — APPROVED** [review]
Looks good.

**Comment by smaslov-intel** [comment]
@againull : can you merge this please?

**Pull request merged**
