### PR TITLE
[SYCL][Doc] Add test plan for dynamic linking feature

### PR DESCRIPTION
**Pull request by Fznamznon**

### CODE REVIEW

**Review by AlexeySachkov — APPROVED** [review]

**Comment by romanovvlad** [comment]
Do we support app(kernel) + dlopen + lib(SYCL_EXTERNAL) case, where kernel deps on SYCL_EXTERNAL from lib?
Sorry if missed this case in the doc.

**Comment by AlexeySachkov** [comment]
> Do we support app(kernel) + dlopen + lib(SYCL_EXTERNAL) case, where kernel deps on SYCL_EXTERNAL from lib?
> Sorry if missed this case in the doc.

Could you please clarify the use-case? Dependency on SYCL_EXTERNAL means that library *must* be linked as well in order for host part of the app to be linked without errors and if we have linked the library, what is the reason for dynamically loading it again?

**Comment by romanovvlad** [comment]
> 
> 
> > Do we support app(kernel) + dlopen + lib(SYCL_EXTERNAL) case, where kernel deps on SYCL_EXTERNAL from lib?
> > Sorry if missed this case in the doc.
> 
> Could you please clarify the use-case? Dependency on SYCL_EXTERNAL means that library _must_ be linked as well in order for host part of the app to be linked without errors and if we have linked the library, what is the reason for dynamically loading it again?

From you answer I infer that this case is not supported. But still try to clarify:
1. libA defines SYCL_EXTERNAL function `foo`
2. An app has a kernel which depends on the `foo` defined in libA
3. The app dlopen's libA (libA is not linked during compilation to the app!!)
4. The app runs the kernel

**Comment by Fznamznon** [comment]
@romanovvlad

> The app dlopen's libA (libA is not linked during compilation to the app!!)

This is not supported by regular C++. There will be a link error.

**Review by romanovvlad — APPROVED** [review]

**Pull request merged**
