### PR TITLE
[SYCL] Update test for new mode SYCL_PI_LEVEL_ZERO_DEVICE_SCOPE_EVENTS=2

### PR DESCRIPTION
**Pull request by smaslov-intel**
E2E test for https://github.com/intel/llvm/pull/5354
Signed-off-by: Sergey V Maslov <sergey.v.maslov@intel.com>

### CODE REVIEW

**Review by sergey-semenov — APPROVED** [review]
LGTM

**Comment by smaslov-intel** [comment]
moved to https://github.com/intel/llvm-test-suite/pull/771

**Pull request closed without merging**
