### PR TITLE
[SYCL] Temporary disable of DeviceLib tests

### PR DESCRIPTION
**Pull request by denis-kabanov**
Disabled tests: SYCL/DeviceLib/built-ins/vector_relational.cpp, SYCL/DeviceLib/cmath_fp64_test.cpp, SYCL/DeviceLib/cmath_test.cpp, SYCL/DeviceLib/math_fp64_test.cpp, SYCL/DeviceLib/math_test.cpp

### CODE REVIEW

**Comment by vzakhari** [comment]
Can you please explain why you have to do it?

**Comment by denis-kabanov** [comment]
> Can you please explain why you have to do it?

All the last PRs to llvm-test-suite fail on these tests.

**Review by dm-vodopyanov — DISMISSED** [review]

**Comment by dm-vodopyanov** [comment]
Can you also please disable Assert tests in separate PR? Please add links to these PRs to appropriate internal tickets.

**Comment by denis-kabanov** [comment]
> Can you also please disable Assert tests in separate PR? Please add links to these PRs to appropriate internal tickets.

I think disabling the assert tests is unnecessary because the latest PRs into llvm-test-suite don't fails on asserts anymore (maybe, they are already fixed).

**Review by vladimirlaz — APPROVED** [review]

**Pull request merged**
