### PR TITLE
[SYCL] Fix missing Unix tools on Windows

### PR DESCRIPTION
**Pull request by alexbatashev**
Use `echo` instead of `true` and check for other tools availability

### CODE REVIEW

**Comment by bader** [comment]
Why these tests use Linux tool in the first place? Can't we write tests using just LLVM tools?

**Comment by steffenlarsen** [comment]
I ran the tests on Windows and most tests now pass. The failing tests fall into two errors, which I suspect are related:

- Regression/pi_release.cpp
- InorderQueue/in_order_property_trace.cpp
- Basic/event_release.cpp
- Scheduler/InOrderQueueDeps.cpp
- Basic/use_pinned_host_memory.cpp
- Basic/queue/release.cpp
- Scheduler/ReleaseResourcesTest.cpp
- Tracing/pi_tracing_test.cpp
- Scheduler/MemObjRemapping.cpp
- Basic/info_ocl_version.cpp
- Tracing/buffer_printers.cpp

Fail with:
```
...
$ "env" "SYCL_PI_TRACE=-1" "echo" "C:\Path\to\tests\Output\test_name.cpp.tmp.out"
# command stderr:
Error: 'env' cannot call 'echo'
error: command failed with exit status: 127
```

- Basic/buffer/native_buffer_creation_flags.cpp

Fail with:
```
...
$ ":" "RUN: at line 2"
$ "echo" "SYCL_PI_TRACE=-1" "C:\Path\to\tests\Output\test_name.cpp.tmp.out"
# command stderr:
stdin and stderr redirects not supported for echo
error: command failed with exit status: 127
```

**Comment by romanovvlad** [comment]
As an option we could try to use  `echo "1" ||` as a substitution. It won't work if the line itself has `&&`.

**Comment by vladimirlaz** [comment]
@alexbatashev have you tried to use LIT shell? It can be set using line like:
```
./llvm-spirv/test/lit.cfg.py:config.test_format = lit.formats.ShTest(not llvm_config.use_lit_shell)
```

**Comment by bader** [comment]
@alexbatashev, please, resolve merge conflicts.

**Review by kbobrovs — APPROVED** [review]
SpecConstants/1.2.1 LGTM

**Comment by bader** [comment]
> @alexbatashev, please, resolve merge conflicts.

@alexbatashev, ping.

**Comment by alexbatashev** [comment]
Decided to split in parts to make it more manageable 
Part 1: https://github.com/intel/llvm-test-suite/pull/475

**Pull request closed without merging**
