### PR TITLE
[SYCL] Fix SYCL_DEVICE_FILTER setting

### PR DESCRIPTION
**Pull request by bso-intel**
Signed-off-by: Byoungro So <byoungro.so@intel.com>

### CODE REVIEW

**Comment by bso-intel** [comment]
@vladimirlaz 
There are several test failures for pre-ci-linux.
I am not sure how my change in one unit test DataMovement.cpp affects other tests.
I am pretty sure my change is irrelevant to these failures.
I already tried to re-runj the test, but it keeps failing.
Any suggestion?

**Comment by bso-intel** [comment]
I see that another PR is also suffering from these unrelated failures on linux.
https://github.com/intel/llvm-test-suite/pull/206

**Comment by vladimirlaz** [comment]
I have restarted the test. Will see what happen

**Comment by bso-intel** [comment]
@vladimirlaz 
Thanks. All checks passed now.
Could you approve and merge this? 
Thanks.

**Comment by bso-intel** [comment]
@vladimirlaz 
I removed the RUN line per your request.

**Review by vladimirlaz — APPROVED** [review]

**Pull request merged**
