### PR TITLE
[SYCL] Test rework for SYCL_DEVICE_FILTER=device_num

### PR DESCRIPTION
**Pull request by KseniyaTikhomirova**
Regression test now partly duplicates RT logic of device choice and
should catch any regressions there.

Signed-off-by: Tikhomirova, Kseniya <kseniya.tikhomirova@intel.com>

### CODE REVIEW

**Comment by KseniyaTikhomirova** [comment]
@bso-intel Could you please review new test design aligned with expected RT behavior?

**Comment by KseniyaTikhomirova** [comment]
few notes about pre-commit checks:
1) please pay attention to check with dependent pull request otherwise device_num test fails.
2) failed checks there is caused by known issues and https://github.com/intel/llvm-test-suite/pull/785 and https://github.com/intel/llvm-test-suite/pull/783 disables them.

@bso-intel could you please review the test?

**Review by bso-intel — APPROVED** [review]
LGTM.

**Comment by KseniyaTikhomirova** [comment]
hi @intel/llvm-reviewers-runtime, this commit depends on https://github.com/intel/llvm/pull/5349, tests with it are passed, could you please take a look and merge if no concerns?

**Review by vladimirlaz — APPROVED** [review]

**Pull request merged**
