### PR TITLE
[SYCL] Update part of the tests to make double support optional

### PR DESCRIPTION
**Pull request by romanovvlad**

### CODE REVIEW

**Comment by v-klochkov** [comment]
Looks good to me, but isn't this fix a subset of a bigger fix (https://github.com/intel/llvm-test-suite/pull/1150) being reviewed and waiting for approval?

**Comment by romanovvlad** [comment]
> Looks good to me, but isn't this fix a subset of a bigger fix (#1150) being reviewed and waiting for approval?

That's right. This patch suggests an alternative solution. It covers only part of the tests to demonstrate approach.

**Comment by kbobrovs** [comment]
`if (device.has(sycl::aspect::fp64)`-based approach can be risky. Tests may be reported as `PASSED` not really running `double` test cases, so I'd rather separate out tests using `double` and have them reported as `UNSUPPORTED`. On the other hand, we don't want to have code duplication. So what we could do is to create pairs of tests:

test.cpp:
```
// to avoid running same test cases in test.cpp and test_double.cpp
// REQUIRES: !sycl-aspect-fp64
...
int_test_case();
float_test_case();
#ifdef USE_FP64
  fp64_test_case();
#endif
...
```
test_double.cpp
```
// REQUIRES: sycl-aspect-fp64
#define USE_FP64
#include "test.cpp"
```
in this case either test.cpp or test_double.cpp will be reported as "UNSUPPORTED" depending on fp64 support by the test platform.

**Comment by romanovvlad** [comment]
> `if (device.has(sycl::aspect::fp64)`-based approach can be risky. Tests may be reported as `PASSED` not really running `double` test cases, so I'd rather separate out tests using `double` and have them reported as `UNSUPPORTED`. 

Not sure that not testing doubles but having "UNSUPPORTED" tests is a way better than not testing doubles and reporting "PASSED"(we could also add a message from the test saying that doubles are skipped).

We already have similar cases in the code base: fp16, image, atomic64, ext_oneapi_cuda_async_barrier. So, if we go with LIT features way (`// REQUIRES: sycl-aspect-fp64`) we would need to do similar LIT features for all tests that require some device feature.

Also, I'm not really sure how we can implement that. Let's say we are going to test `cuda be, l0 gpu, opencl gpu, opencl cpu` and one target from this list(`opencl cpu`) doesn't support a feature, should we run a test for all targets or we should skip the test completely?

**Comment by AlexeySachkov** [comment]
> > `if (device.has(sycl::aspect::fp64)`-based approach can be risky. Tests may be reported as `PASSED` not really running `double` test cases, so I'd rather separate out tests using `double` and have them reported as `UNSUPPORTED`.
> 
> Also, I'm not really sure how we can implement that. Let's say we are going to test `cuda be, l0 gpu, opencl gpu, opencl cpu` and one target from this list(`opencl cpu`) doesn't support a feature, should we run a test for all targets or we should skip the test completely?

I agree with @romanovvlad here: list of supported aspects is a property of a device and we can have more than one device available on our systems. I suggest that we go with the approach Vlad implemented in this PR, because it should save us more machine time during testing. Moreover, when optional kernel features will be implemented, we should be able to remove per-kernel device code split from all tests.

**Review by v-klochkov — APPROVED** [review]

**Pull request merged**
