### PR TITLE
Add named_barriers tests

### PR DESCRIPTION
**Pull request by fveselov**
Tests on named_barriers for PVC migrate from closed repo

### CODE REVIEW

**Comment by kbobrovs** [comment]
@fveselov, sorry for delay. Did you run the tests on PVC?

**Comment by fveselov** [comment]
@kbobrovs, yes.
There were some issues that didn't show up running on simulator, but they were fixed. Currently all tests pass on PVC-XT HW.

**Review by kbobrovs — APPROVED** [review]

**Comment by pvchupin** [comment]
Tests fail on esimd_emulator in unrelated pre-commit testing. Reverted.

**Comment by kbobrovs** [comment]
@fveselov, the patch was reverted because tests failed on emulator. Did you run them on emulator? Please remove "|| esimd_emulator" everywhere and add a TODO, and create a new PR
@dongkyunahn-intel, FYI

**Comment by kbobrovs** [comment]
Replacement PR: https://github.com/intel/llvm-test-suite/pull/1326

**Pull request merged**
