### PR TITLE
[SYCL] Disable unexpectedly failing test on level zero device scope events

### PR DESCRIPTION
**Pull request by vasilytric**

### CODE REVIEW

**Comment by vasilytric** [comment]
@smaslov-intel would you mind to merge this PR?

**Comment by smaslov-intel** [comment]
@vasilytric : this is an important test that I'd like to be run. Where do you see it failing unexpectedly?

**Review by smaslov-intel — CHANGES_REQUESTED** [review]
Please show how it fails

**Comment by vasilytric** [comment]
> Please show how it fails

@smaslov-intel it fails in PR https://github.com/intel/llvm-test-suite/pull/839 on windows CI also in the a few other PRs

**Comment by vasilytric** [comment]
@smaslov-intel Now after re-running all is ok, so this PR will be closed

**Comment by vasilytric** [comment]
Disabled test has been fixed, so disabling is not required

**Pull request closed without merging**
