### PR TITLE
Add feature matrix which is only supported on specific hardware

### PR DESCRIPTION
**Pull request by yuxianch**

### CODE REVIEW

**Review by romanovvlad — APPROVED** [review]
LGTM, but would like @dkhaldi to approve as well

**Review by dkhaldi — APPROVED** [review]
LGTM

**Comment by yuxianch** [comment]
The failure in pre-ci-cuda is not related with this change.
```
[2021-07-30T06:39:27.415Z] ******************** TEST 'SYCL :: Regression/unoptimized_stream.cpp' FAILED ********************
[2021-07-30T06:39:27.415Z] Script:
[2021-07-30T06:39:27.415Z] --
[2021-07-30T06:39:27.415Z] : 'RUN: at line 1';    /localdisk2/llvm-test-suite_Jenkins/workspace/LLVM-Test-Suite-CI-TMP/LLVM-Test-Suite-CUDA/llvm.obj/bin/clang++      -fsycl -fsycl-targets=nvptx64-nvidia-cuda-sycldevice /localdisk2/llvm-test-suite_Jenkins/workspace/LLVM-Test-Suite-CI-TMP/LLVM-Test-Suite-CUDA/llvm-test-suite/SYCL/Regression/unoptimized_stream.cpp -O0 -o /localdisk2/llvm-test-suite_Jenkins/workspace/LLVM-Test-Suite-CI-TMP/LLVM-Test-Suite-CUDA/build/SYCL/Regression/Output/unoptimized_stream.cpp.tmp.out
[2021-07-30T06:39:27.415Z] : 'RUN: at line 2';   true /localdisk2/llvm-test-suite_Jenkins/workspace/LLVM-Test-Suite-CI-TMP/LLVM-Test-Suite-CUDA/build/SYCL/Regression/Output/unoptimized_stream.cpp.tmp.out
[2021-07-30T06:39:27.415Z] : 'RUN: at line 3';   true /localdisk2/llvm-test-suite_Jenkins/workspace/LLVM-Test-Suite-CI-TMP/LLVM-Test-Suite-CUDA/build/SYCL/Regression/Output/unoptimized_stream.cpp.tmp.out
[2021-07-30T06:39:27.415Z] : 'RUN: at line 4';    env SYCL_DEVICE_FILTER=cuda:gpu,host  /localdisk2/llvm-test-suite_Jenkins/workspace/LLVM-Test-Suite-CI-TMP/LLVM-Test-Suite-CUDA/build/SYCL/Regression/Output/unoptimized_stream.cpp.tmp.out
[2021-07-30T06:39:27.415Z] --
[2021-07-30T06:39:27.415Z] Exit Code: -6
[2021-07-30T06:39:27.415Z] 
[2021-07-30T06:39:27.415Z] Command Output (stdout):
[2021-07-30T06:39:27.415Z] --
[2021-07-30T06:39:27.415Z] $ ":" "RUN: at line 1"
[2021-07-30T06:39:27.415Z] note: command had no output on stdout or stderr
[2021-07-30T06:39:27.416Z] $ "/localdisk2/llvm-test-suite_Jenkins/workspace/LLVM-Test-Suite-CI-TMP/LLVM-Test-Suite-CUDA/llvm.obj/bin/clang++" "-fsycl" "-fsycl-targets=nvptx64-nvidia-cuda-sycldevice" "/localdisk2/llvm-test-suite_Jenkins/workspace/LLVM-Test-Suite-CI-TMP/LLVM-Test-Suite-CUDA/llvm-test-suite/SYCL/Regression/unoptimized_stream.cpp" "-O0" "-o" "/localdisk2/llvm-test-suite_Jenkins/workspace/LLVM-Test-Suite-CI-TMP/LLVM-Test-Suite-CUDA/build/SYCL/Regression/Output/unoptimized_stream.cpp.tmp.out"
[2021-07-30T06:39:27.416Z] note: command had no output on stdout or stderr
[2021-07-30T06:39:27.416Z] $ ":" "RUN: at line 2"
[2021-07-30T06:39:27.416Z] note: command had no output on stdout or stderr
[2021-07-30T06:39:27.416Z] $ "true" "/localdisk2/llvm-test-suite_Jenkins/workspace/LLVM-Test-Suite-CI-TMP/LLVM-Test-Suite-CUDA/build/SYCL/Regression/Output/unoptimized_stream.cpp.tmp.out"
[2021-07-30T06:39:27.416Z] note: command had no output on stdout or stderr
[2021-07-30T06:39:27.416Z] $ ":" "RUN: at line 3"
[2021-07-30T06:39:27.416Z] note: command had no output on stdout or stderr
[2021-07-30T06:39:27.416Z] $ "true" "/localdisk2/llvm-test-suite_Jenkins/workspace/LLVM-Test-Suite-CI-TMP/LLVM-Test-Suite-CUDA/build/SYCL/Regression/Output/unoptimized_stream.cpp.tmp.out"
[2021-07-30T06:39:27.416Z] note: command had no output on stdout or stderr
[2021-07-30T06:39:27.416Z] $ ":" "RUN: at line 4"
[2021-07-30T06:39:27.416Z] note: command had no output on stdout or stderr
[2021-07-30T06:39:27.416Z] $ "env" "SYCL_DEVICE_FILTER=cuda:gpu,host" "/localdisk2/llvm-test-suite_Jenkins/workspace/LLVM-Test-Suite-CI-TMP/LLVM-Test-Suite-CUDA/build/SYCL/Regression/Output/unoptimized_stream.cpp.tmp.out"
[2021-07-30T06:39:27.416Z] # command stderr:
[2021-07-30T06:39:27.416Z] 
[2021-07-30T06:39:27.416Z] PI CUDA ERROR:
[2021-07-30T06:39:27.416Z] 	Value:           4
[2021-07-30T06:39:27.416Z] 	Name:            terminate called after throwing an instance of 'cl::sycl::runtime_error'
[2021-07-30T06:39:27.416Z]   what():  Native API failed. Native API returns: -999 (Unknown OpenCL error code) -999 (Unknown OpenCL error code)
[2021-07-30T06:39:27.416Z] 
[2021-07-30T06:39:27.416Z] error: command failed with exit status: -6
[2021-07-30T06:39:27.416Z] 
[2021-07-30T06:39:27.416Z] --
```

**Comment by romanovvlad** [comment]
@yuxianch Could you please disable the failed test on Cuda?

**Comment by yuxianch** [comment]
> @yuxianch Could you please disable the failed test on Cuda?

The issue is reported in https://github.com/intel/llvm-test-suite/issues/387
I will disable the failed test later.

**Comment by yuxianch** [comment]
> > @yuxianch Could you please disable the failed test on Cuda?
> 
> The issue is reported in #387
> I will disable the failed test later.

Disable the failed test on CUDA in https://github.com/intel/llvm-test-suite/pull/392

**Pull request merged**
