### PR TITLE
[SYCL] disable ze_debug=4 test

### PR DESCRIPTION
**Pull request by bso-intel**
This test expects to throw an exception.
So, there is no corresponding call to deallocation of PiModule. We need to disable this test from ZE_DEBUG=4 test.

Signed-off-by: Byoungro So <byoungro.so@intel.com>

### CODE REVIEW

**Comment by bso-intel** [comment]
pre-ci-windows failures are unrelated to my changeset.

**Comment by bso-intel** [comment]
@sergey-semenov 
friendly ping

**Comment by sergey-semenov** [comment]
@bso-intel Sorry about the delay. I'm not sure I get the reasoning behind expecting this to fail with ZE_DEBUG=4. Could you elaborate on this a bit? Which release call is missing here?

**Comment by bso-intel** [comment]
PiModuleDestroy is called correctly, but when there is exception thrown, llvm-lit tears down the runtime early.
This issue is only with llvm-lit.
When we run it directly, the proper piModuleDestroy is called and there is no memory leak.

**Review by sergey-semenov — APPROVED** [review]

**Pull request merged**
