### PR TITLE
do not rely on experimental CreateMultipleRootDevices

### PR DESCRIPTION
**Pull request by smaslov-intel**
Signed-off-by: Sergey V Maslov <sergey.v.maslov@intel.com>

### CODE REVIEW

**Review by KseniyaTikhomirova — APPROVED** [review]

**Comment by smaslov-intel** [comment]
The only fail is known and tracked, so this PR can be merged:
> Failed Tests (1):
[2023-01-04T18:17:15.937Z]   SYCL :: SubGroupMask/Basic.cpp

**Pull request merged**
