### PR TITLE
[ESIMD] Enabled back kmeans test by reducing the number of iterations

### PR DESCRIPTION
**Pull request by DenisBakhvalov**

### CODE REVIEW

**Comment by vladimirlaz** [comment]
@DenisBakhvalov, @kbobrovs Does it make sense to have multiple iterations here as soon as these tests are functional? Remove iterative execution will save extra CI resources.

**Comment by kbobrovs** [comment]
@vladimirlaz - seems like a good point to me. adding @kychendev for possible comments.

**Comment by kychendev** [comment]
KMeans algorithm requires multiple iterations for the centroids to converge. Reducing the number of iterations may result in poor results, although it wouldn't affect validation as we are comparing with CPU processing output after the same number of iterations. Was this test disabled due to time out issue? Another way could be to reduce the input size.

**Comment by kbobrovs** [comment]
> KMeans algorithm requires multiple iterations for the centroids to converge. Reducing the number of iterations may result in poor results, although it wouldn't affect validation as we are comparing with CPU processing output after the same number of iterations. Was this test disabled due to time out issue? Another way could be to reduce the input size.

Thanks for clarification. Yes, the test was disabled due to timeout (which maybe a sign of perf degradation, but this is another problem).
So I think as long as we can reliably verify results accuracy doesn't matter in this case. So I'd say reduce to few iterations (and possibly input size too if it can be done easily, otherwise as a subsequent PR).

**Review by kbobrovs — APPROVED** [review]

**Comment by kbobrovs** [comment]
Approving, as the patch fixes the immediate problem, and further improvements can be done atop. Leave to @vladimirlaz.

**Pull request merged**
