### PR TITLE
[SYCL] Add and adjust tests for SYCL 2020 multi_ptr

### PR DESCRIPTION
**Pull request by steffenlarsen**
This commit adjusts a number of existing using `multi_ptr` and adds new tests for new interfaces.

intel/llvm changes: https://github.com/intel/llvm/pull/6893

### CODE REVIEW

**Comment by steffenlarsen** [comment]
@Pennycook & @againull - Friendly ping.

**Comment by Pennycook** [comment]
Sorry for the delay and thanks for the ping.

Can you say a little bit about why some of the changes use the `legacy` decoration and some of them use `yes`?

**Comment by steffenlarsen** [comment]
> Can you say a little bit about why some of the changes use the `legacy` decoration and some of them use `yes`?

Extensions with functionality that returns `multi_ptr` will return `legacy` until they have been changed. This is because the new `multi_ptr` implementation defaults the `access::decorated` template argument to `legacy` for backwards compatibility. So in principle, the cases here where `legacy` is used could stay unchanged, but I think it's better to be explicit, to make it simpler to transition to not having a default `access::decorated` value in the future.

As for the extensions, I think we need to consider how to transition these interfaces to use the non-legacy versions, then return to these and adjust accordingly.

**Comment by Pennycook** [comment]
Ah, I see.  I'd missed that all the `legacy` usages were for return values.  That makes sense, thanks for the explanation.

**Review by Pennycook — APPROVED** [review]

**Comment by steffenlarsen** [comment]
@againull - Friendly ping.

**Review by againull — APPROVED** [review]
I'm so sorry.

**Pull request merged**
