### PR TITLE
[SYCL] Remove 6 ESIMD and InlineAsm tests' XFAIL when GPU uplift

### PR DESCRIPTION
**Pull request by yanfeng3721**
The following 6 tests begin to PASS after intel/llvm#3386
4 tests unexpected pass on level_zero:gpu
SYCL :: ESIMD/spec_const/spec_const_char.cpp
SYCL :: ESIMD/spec_const/spec_const_short.cpp
SYCL :: ESIMD/spec_const/spec_const_uchar.cpp
SYCL :: ESIMD/spec_const/spec_const_ushort.cpp
2 tests unexpected pass on level_zero:gpu/opencl:gpu
SYCL :: InlineAsm/asm_loop.cpp
SYCL :: InlineAsm/asm_switch.cpp

Remove llvm-test-suite "//XFAIL: level_zero" for ESIMD test, and "//XFAIL:*" for InlineAsm test.

### CODE REVIEW

**Review by kbobrovs — DISMISSED** [review]
Please change PR title - this is not what the patch is actually doing.

**Comment by kbobrovs** [comment]
@smaslov-intel, do you know what recent changes in level-zero lead to specialization constants tests passing?

**Comment by smaslov-intel** [comment]
> @smaslov-intel, do you know what recent changes in level-zero lead to specialization constants tests passing?

No idea. There haven't been any works recently specifically related to spec consts.
How were they failing previously?

**Comment by kbobrovs** [comment]
> How were they failing previously?

@yanfeng3721 - redirect the q to you.

**Comment by yanfeng3721** [comment]
> > How were they failing previously?
> 
> @yanfeng3721 - redirect the q to you.

With uplift Linux GPU RT >=21.11.19310(also required Level zero loader v1.2.3), the 6 test could pass.

**Comment by kbobrovs** [comment]
> > > How were they failing previously?
> > 
> > 
> > @yanfeng3721 - redirect the q to you.
> 
> With uplift Linux GPU RT >=21.11.19310(also required Level zero loader v1.2.3), the 6 test could pass.

@yanfeng3721, how the tests were failing previously - what was the diagnostics?

**Comment by yanfeng3721** [comment]
> > > > How were they failing previously?
> > > 
> > > 
> > > @yanfeng3721 - redirect the q to you.
> > 
> > 
> > With uplift Linux GPU RT >=21.11.19310(also required Level zero loader v1.2.3), the 6 test could pass.
> 
> @yanfeng3721, how the tests were failing previously - what was the diagnostics?

Thanks for your review. 
I think the previous fail is only reproduced with GUP RT 21.09.19150 and lower(please see the following error log), we need to uplift GPU RT with latest version 21.11.19310(intel/llvm#3386), it is better to merge the https://github.com/intel/llvm-test-suite/pull/232 at the same time. And I have asked @vladimirlaz to help to merge those PR at the same time if it has been approved. 
Driver version  : 21.09.19150
-- Testing: 1 tests, 1 workers --
XFAIL: SYCL :: ESIMD/spec_const/spec_const_char.cpp (1 of 1)
Exit Code: -6
Command Output (stdout):

**Comment by kbobrovs** [comment]
> spec_const/spec_const_char.cpp

OK, here is how this test failed before:

```
spec_const_char.cpp.tmp.out: .../llvm-spirv-vc/lib/SPIRV/SPIRVReader.cpp:1350:
llvm::Value* SPIRV::SPIRVToLLVM::transValueWithoutDecoration(SPIRV::SPIRVValue*, llvm::Function*, llvm::BasicBlock*, bool):
Assertion
`(BT->getBitWidth() == 64 || (ConstValue >> BT->getBitWidth()) == 0) && "Size of externally provided specialization constant value doesn't" "fit into the specialization constant type"'
failed.

error: command failed with exit status: -6
```
Looks like OpenCL and LevelZero used different SPIRV readers.

**Review by kbobrovs — APPROVED** [review]
I approve the esimd part.

**Pull request merged**
