### PR TITLE
[SYCL][ESIMD] Fix test failure on emulator

### PR DESCRIPTION
**Pull request by fineg74**

### CODE REVIEW

**Review by sarnex — APPROVED** [review]
Hey, do we have an internal jira tracking the root cause? Thanks

**Comment by fineg74** [comment]
> Hey, do we have an internal jira tracking the root cause? Thanks

Not sure, the test works fine on HW but fails on emulator. I am not sure who owns the emulator.

**Comment by fineg74** [comment]
Validation failure on Linux and Windows: OptionalKernelFeatures/is_compatible.cpp is not related to the change

**Comment by sarnex** [comment]
> Not sure, the test works fine on HW but fails on emulator. I am not sure who owns the emulator.

Gotcha, thanks

**Pull request merged**
