### PR TITLE
[SYCL] expand group_broadcast testing for new update

### PR DESCRIPTION
**Pull request by cperkinsintel**
there are spec clarifications that widen the allowable types that can be passed to `group_broadcast`   Here we are re-enabling these tests which will pass once the matching update (https://github.com/intel/llvm/pull/4910)  is merged on intel/llvm

These expanded tests running (and passing) against supporting commit here: http://icl-jenkins.sc.intel.com:8080/job/SYCL_CI/job/intel/job/Lin/job/LLVM_Test_Suite/7729/

Signed-off-by: Chris Perkins <chris.perkins@intel.com>

### CODE REVIEW

**Review by Pennycook — DISMISSED** [review]

**Comment by cperkinsintel** [comment]
@vladimirlaz is /verify a directive to the CI?

I ran 4910 against this test PR here (where it passed): http://icl-jenkins.sc.intel.com:8080/job/SYCL_CI/job/intel/job/Lin/job/LLVM_Test_Suite/7729/

**Comment by cperkinsintel** [comment]
I believe this fix is now needed to get the post-commit failures cleared.

**Comment by vladimirlaz** [comment]
> @vladimirlaz is /verify a directive to the CI?
> 
> I ran 4910 against this test PR here (where it passed): http://icl-jenkins.sc.intel.com:8080/job/SYCL_CI/job/intel/job/Lin/job/LLVM_Test_Suite/7729/

@Pennycook this is newly added feature which allows to run changes in 2 PRs. the results are available in Jenkins/llvm-test-suite job.

**Review by vladimirlaz — APPROVED** [review]

**Pull request merged**
