### PR TITLE
Test bfloat16 fmax fmin

### PR DESCRIPTION
**Pull request by jinge90**
This PR is test for https://github.com/intel/llvm/pull/7732

### CODE REVIEW

**Review by AlexeySachkov — APPROVED** [review]

**Comment by jinge90** [comment]
Hi, @pvchupin 
Could you take a look at this PR? The pre-ci failed due to other issues:

[2022-12-21T01:55:54.907Z] terminate called after throwing an instance of 'sycl::_V1::runtime_error'

[2022-12-21T01:55:54.907Z]   what():  No device of requested type available. -1 (PI_ERROR_DEVICE_NOT_FOUND)
Many unrelated test failed due to runtime error above.
Thanks very much.

**Comment by JackAKirk** [comment]
There's some overlap here with https://github.com/intel/llvm-test-suite/blob/intel/SYCL/BFloat16/bfloat16_builtins.cpp, where fmin and fmax are also tested. The test was written when only the cuda backend was supported, but should now pass for all backends with the generic impls. Would it make sense to coalesce these two test files into a single file and enable it for all backends?
Thanks

**Comment by jinge90** [comment]
> There's some overlap here with https://github.com/intel/llvm-test-suite/blob/intel/SYCL/BFloat16/bfloat16_builtins.cpp, where fmin and fmax are also tested. The test was written when only the cuda backend was supported, but should now pass for all backends with the generic impls. Would it make sense to coalesce these two test files into a single file and enable it for all backends? Thanks

I didn't realize that we have already had tests, it makes sense to coalesce these 2 test, I will do it soon.
Thanks very much.

**Comment by againull** [comment]
> > There's some overlap here with https://github.com/intel/llvm-test-suite/blob/intel/SYCL/BFloat16/bfloat16_builtins.cpp, where fmin and fmax are also tested. The test was written when only the cuda backend was supported, but should now pass for all backends with the generic impls. Would it make sense to coalesce these two test files into a single file and enable it for all backends? Thanks
> 
> I didn't realize that we have already had tests, it makes sense to coalesce these 2 test, I will do it soon. Thanks very much.

@jinge90 Thanks a lot! Do you prefer to get this PR merged and do coalescing in a separate PR? Or do you prefer to do coalescing in this PR?

**Comment by jinge90** [comment]
> > > There's some overlap here with https://github.com/intel/llvm-test-suite/blob/intel/SYCL/BFloat16/bfloat16_builtins.cpp, where fmin and fmax are also tested. The test was written when only the cuda backend was supported, but should now pass for all backends with the generic impls. Would it make sense to coalesce these two test files into a single file and enable it for all backends? Thanks
> > 
> > 
> > I didn't realize that we have already had tests, it makes sense to coalesce these 2 test, I will do it soon. Thanks very much.
> 
> @jinge90 Thanks a lot! Do you prefer to get this PR merged and do coalescing in a separate PR? Or do you prefer to do coalescing in this PR?

Hi, @againull 
I will close this PR and create a new one.
Thanks very much.

**Pull request closed without merging**
