### PR TITLE
Skip tests hanging on dGPUs. These 2 tests will hang succeeding tests

### PR DESCRIPTION
**Pull request by jiezzhang**

### CODE REVIEW

**Comment by kychendev** [comment]
@jiezzhang , we also need to skip another esimd test case - "histogram_raw_send".

**Comment by jiezzhang** [comment]
@kychendev I found your commit just now. I have updated the PR. "histogram_raw_send" has been skipped correctly

**Comment by vladimirlaz** [comment]
@jiezzhang if the PR is still needed could you please resolve conflicts? Otherwise it can be closed

**Comment by vladimirlaz** [comment]
@jiezzhang, ping

**Comment by jiezzhang** [comment]
No longer need this PR. Close

**Pull request closed without merging**
