### PR TITLE
[SYCL][ESIMD][EMU] Removing 'XFAIL' markings for 'single_task' tests

### PR DESCRIPTION
**Pull request by dongkyunahn-intel**
- 'single_task()' is enabled for ESIMD_EMULATOR backend in intel/llvm

### CODE REVIEW

**Comment by dongkyunahn-intel** [comment]
Defer until https://github.com/intel/llvm/pull/5677 is merged in intel/llvm.

**Comment by dongkyunahn-intel** [comment]
@kbobrovs , @vladimirlaz , please merge this PR.

Enabling ESIMD_EMULATOR during CI (https://github.com/intel/llvm/pull/5677) fails because of unexpected passes whose 'XFAIL' markings are removed in this PR.

**Review by kbobrovs — DISMISSED** [review]

**Review by kbobrovs — APPROVED** [review]

**Comment by dongkyunahn-intel** [comment]
@kbobrovs , would you merge this PR? All checks have passed after retrying.

**Review by kbobrovs — APPROVED** [review]

**Pull request merged**
