### PR TITLE
[SYCL][ESIMD] Enhance enum logging support

### PR DESCRIPTION
**Pull request by yuriykoch**
Provides two major API enhancements:
- `value_pack::generate_named_by` - to use custom stringification functions
- `log::StringMaker` specialization support

Note that any `StringMaker` specialization will be automatically used within `value_pack::generate_named(void)` call

Also fixes compilation with `ESIMD_TESTS_VERBOSE_LOG` enabled

Signed-off-by: Kochetkov, Yuriy <yuriyx.kochetkov@intel.com>

### CODE REVIEW

**Comment by yuriykoch** [comment]
@vasilytric Would you mind to take a look?

**Comment by yuriykoch** [comment]
@sndmitriev Would you mind to take a look?

**Comment by yuriykoch** [comment]
@sndmitriev Friendly ping as #921 depends on it

**Review by sndmitriev — APPROVED** [review]
LGTM

**Comment by yuriykoch** [comment]
Thanks :) @kbobrovs Would you mind to merge this PR?

**Pull request merged**
