### PR TITLE
[SYCL][Level Zero] Add a test for sycl_ext_intel_queue_index extension

### PR DESCRIPTION
**Pull request by aelovikov-intel**
Implementation: https://github.com/intel/llvm/pull/7599.

### CODE REVIEW

**Review by gmlueck — APPROVED** [review]
LGTM

**Review by againull — APPROVED** [review]

**Review by smaslov-intel — APPROVED** [review]

**Comment by aelovikov-intel** [comment]
The test has been verified as part of the "verify with" testing in https://github.com/intel/llvm/pull/7599 and can be merged together with it.

**Comment by steffenlarsen** [comment]
> The test has been verified as part of the "verify with" testing in [intel/llvm#7599](https://github.com/intel/llvm/pull/7599) and can be merged together with it.

Testing on Windows appear to be stuck on this PR, but as @aelovikov-intel mentions it has been verified with the merged changed.

**Pull request merged**
