### PR TITLE
[SYCL] test for barrier submission: https://github.com/intel/llvm/pul…

### PR DESCRIPTION
**Pull request by smaslov-intel**
Test for barrier submission in https://github.com/intel/llvm/pull/3045

Signed-off-by: Sergey V Maslov <sergey.v.maslov@intel.com>

### CODE REVIEW

**Review by bso-intel — DISMISSED** [review]
LGTM, although this is a very corner case where no command is created before the barrier.

**Comment by vladimirlaz** [comment]
@smaslov-intel the test is passing without #3000 fix. Is it expected?

**Comment by smaslov-intel** [comment]
> @smaslov-intel the test is passing without #3000 fix. Is it expected?

Good catch. This was unexpected, and was caused by the fact host device was used.
I changed the test to use "default_selector". It should hang with the https://github.com/intel/llvm/pull/3045 compiler fix.

**Review by bso-intel — DISMISSED** [review]
Now, it expectedly failed.
LGTM

**Comment by vladimirlaz** [comment]
The test will be submitted after retest with nightly containing product change.

**Comment by vladimirlaz** [comment]
@smaslov-intel, could you please fix failure on CUDA?

**Review by vladimirlaz — CHANGES_REQUESTED** [review]
@smaslov-intel, could you please fix failure on CUDA?

**Comment by smaslov-intel** [comment]
> @smaslov-intel, could you please fix failure on CUDA?

@vladimirlaz : I cannot access the http://pre-commit.llvm.intel.com:8010/job/LLVM-Test-Suite-CI/job/LLVM-Test-Suite-CUDA/59/display/redirect (it says Network error). How do I restart the CUDA testing?

**Comment by smaslov-intel** [comment]
The CUDA failure is due to https://github.com/intel/llvm/issues/3218.
I am disabling the new barrier test for CUDA in this PR.

**Review by vladimirlaz — APPROVED** [review]

**Pull request merged**
