### PR TITLE
[SYCL] Add lit test for integer math function abs, labs, llabs

### PR DESCRIPTION
**Pull request by haonanya**
Signed-off-by: haonanya <haonan.yang@intel.com>
This PR aims to add lit test for https://github.com/intel/llvm/pull/3364

### CODE REVIEW

**Review by vzakhari — DISMISSED** [review]

**Comment by vladimirlaz** [comment]
The tests is passing before submission of intel/llvm#3364. I expected that the test should fail until the device library change is submitted.

**Comment by jinge90** [comment]
> The tests is passing before submission of [intel/llvm#3364](https://github.com/intel/llvm/pull/3364). I expected that the test should fail until the device library change is submitted.

Hi, @vladimirlaz 
You are correct, this test should fail without compiler device library abs support. The reason why pass here is in device compilation, FE will convert function call "abs" to llvm.abs intrinsic and llvm-spirv can support this intrinsic now.
We will add "-fno-builtin" to the math test and then all math function call will reside in device code and device library will support them.
Thanks very much.

**Comment by jinge90** [comment]
@haonanya 
Could you add "-fno-builtin" to the building command?

**Review by vladimirlaz — CHANGES_REQUESTED** [review]
@haonanya
Could you add "-fno-builtin" to the building command?

**Comment by haonanya** [comment]
Hi, @vladimirlaz. Sorry for late reply. There are some compiling issues when added "-fno-builtin" to the building command in Windows, we are looking into this issue.
Thanks very much.

**Comment by jinge90** [comment]
Hi, @vladimirlaz 
This test are expected to work when https://github.com/intel/llvm/pull/3472 is merged.
Thanks very much.

**Comment by vladimirlaz** [comment]
The failures below do not correlate with the PR:
 - SYCL :: Regression/implicit_offset_debug_info.cpp
 - SYCL :: USM/pointer_query.cpp

**Review by vladimirlaz — APPROVED** [review]

**Review by vzakhari — APPROVED** [review]

**Pull request merged**
