### PR TITLE
[SYCL] add cases for double vectors in SubGroup tests

### PR DESCRIPTION
**Pull request by maksimsab**

### CODE REVIEW

**Review by Pennycook — APPROVED** [review]

**Review by dm-vodopyanov — APPROVED** [review]

**Comment by bader** [comment]
@maksimsab, I had to revert this change due to regressions in pre-commit on NVIDIA GPU. Please, re-commit after dealing with regressions.

**Comment by maksimsab** [comment]
@bader Then it looks like the corresponding commit from sycl should be reverted as well. BTW, where I could take a look at mentioned regression?

**Comment by dm-vodopyanov** [comment]
> @bader Then it looks like the corresponding commit from sycl should be reverted as well. BTW, where I could take a look at mentioned regression?

E.g., here: https://github.com/intel/llvm/actions/runs/4245219562/jobs/7381010580

**Comment by bader** [comment]
> @bader Then it looks like the corresponding commit from sycl should be reverted as well. BTW, where I could take a look at mentioned regression?

It's possible that feature doesn't work, but right now it's not tested and do not impact validation. If you fix the problem soon, I think we can avoid reverting the DPC++ patch.

**Pull request merged**
