### PR TITLE
[ESIMD] Add new test cases to simd::copy_from/to test

### PR DESCRIPTION
**Pull request by sndmitriev**
This patch adds new test cases to simd::copy_from/to test which
exercise this API on simd objects exceeding eight owords in size.

Signed-off-by: Sergey Dmitriev <serguei.n.dmitriev@intel.com>

### CODE REVIEW

**Review by kbobrovs — APPROVED** [review]

**Review by v-klochkov — APPROVED** [review]

**Comment by sndmitriev** [comment]
I believe test failures on pre-ci-windows testing are not related to this change.

**Comment by sndmitriev** [comment]
@bader, so you know if pre-ci-windows failures are expected right now? I do not think they are related to these changes.

**Comment by bader** [comment]
> @bader, so you know if pre-ci-windows failures are expected right now? I do not think they are related to these changes.

According to my expectations all tests must pass. If you think that failures are not related to you changes, please, file a bug report and disable failing tests to avoid false alarms in CI process.

**Pull request merged**
