### PR TITLE
[SYCL] Fix CUDA tests using bfloat16

### PR DESCRIPTION
**Pull request by steffenlarsen**
SYCL/BFloat16/bfloat16_builtins.cpp, SYCL/Matrix/element_wise_all_ops_bf16.cpp, SYCL/Matrix/element_wise_wi_marray_legacy.cpp are made to use the correct extension namespaces to have both `bfloat16` and the corresponding experimental builtins without namespaces.

SYCL/Matrix/joint_matrix_tensorcores_legacy.cpp is changed to case convert `bfloat` to `float` directly - using the existing `else`-branch - instead of using the removed `bfloat16::raw()` method and custom conversion. 

These test changes require https://github.com/intel/llvm/pull/7567.

### CODE REVIEW

**Comment by steffenlarsen** [comment]
@JackAKirk - Would you be able to help verify that these fix the problems seen in pre-commit CI? For example in https://github.com/intel/llvm/pull/7563.

**Comment by JackAKirk** [comment]
> @JackAKirk - Would you be able to help verify that these fix the problems seen in pre-commit CI? For example in [intel/llvm#7563](https://github.com/intel/llvm/pull/7563).

Yep sure, no problem.

**Comment by JackAKirk** [comment]
> @JackAKirk - Would you be able to help verify that these fix the problems seen in pre-commit CI? For example in [intel/llvm#7563](https://github.com/intel/llvm/pull/7563).

Yes with your two PRs the joint_matrix_tensorcores_legacy.cpp and bfloat16_builtins.cpp are passing. Note that cuda doesn't run on element_wise_all_ops_bf16.cpp. Changes in the tests here look good.

bfloat16_type.cpp is failing locall for me too, as well as Matrix/element_wise_wi_marray_legacy.cpp: Matrix/element_wise_wi_marray_legacy.cpp can probably be removed anyway since I think we are going to scrap this functionality, at least for the time being anyway, because it is not very important and we would have to create a whole new joint_matrix class in an experimental::cuda name to be consistent with scope conventions.

**Review by JackAKirk — APPROVED** [review]

**Comment by steffenlarsen** [comment]
Thanks a ton for checking! 😄 

> bfloat16_type.cpp is failing locall for me too, as well as Matrix/element_wise_wi_marray_legacy.cpp: Matrix/element_wise_wi_marray_legacy.cpp can probably be removed anyway since I think we are going to scrap this functionality, at least for the time being anyway, because it is not very important and we would have to create a whole new joint_matrix class in an experimental::cuda name to be consistent with scope conventions.

bfloat16_type.cpp seems to have been split up into a CUDA variant at some point too as the CUDA backend needs SM80 on the corresponding device, so I've disabled CUDA in that test again and changed the CUDA variant of it slightly to check for SM version. See https://github.com/intel/llvm-test-suite/pull/1423.

For SYCL/Matrix/element_wise_wi_marray_legacy.cpp I suspect there's just a missing `
using namespace sycl::ext::oneapi;`. I will add that to this PR, then we can remove it later if need be.

**Review by AlexeySachkov — APPROVED** [review]

**Review by v-klochkov — APPROVED** [review]

**Pull request merged**
