### PR TITLE
[SYCL] tests to support new sycl::span deduction guide fix

### PR DESCRIPTION
**Pull request by cperkinsintel**
deduction guide for sycl::span has been updated to correctly support construction with type deduction for array args. Here the tests are updated to support this new addition.

Fix on intel/llvm:  https://github.com/intel/llvm/pull/4970

This test change cannot pass without the above PR. Here you can see the two run against each other and passing successfully: http://icl-jenkins.sc.intel.com:8080/job/SYCL_CI/job/intel/job/Lin/job/LLVM_Test_Suite/7736/

Signed-off-by: Chris Perkins <chris.perkins@intel.com>

### CODE REVIEW

**Review by vladimirlaz — APPROVED** [review]

**Review by s-kanaev — APPROVED** [review]
As far as I understand, the test doesn't need to run anything. Hence, is it possible to have such a test as in-tree LIT test?

**Comment by cperkinsintel** [comment]
@s-kanaev  - by "have such a test as an in-tree LIT test"  do  you mean move this test back to intel/llvm as part of the SYCL test suite there?   Yes, easily. Let me know if I understand you correctly.

**Comment by vladimirlaz** [comment]
@cperkinsintel it looks like there is no reason to add the regression test for the issue here. The problem is exposed on compile-time and can be checked in check-sycl.

**Comment by cperkinsintel** [comment]
moving test to check-sycl https://github.com/intel/llvm/pull/5056 . Closing

**Pull request closed without merging**
