### PR TITLE
[SYCL][HIP] Expect failure of some tests that have 'has(aspect::atomic64)'

### PR DESCRIPTION
**Pull request by denis-kabanov**
Expect failure of some tests that have 'has(aspect::atomic64)' because hip backend does not have such check implementation.
PR with specialization removing for atomic64 check: https://github.com/intel/llvm/pull/5430
Github issue for implementating such check on hip backend: https://github.com/intel/llvm/issues/5570
**Should be merged at the same time with mentioned [PR](https://github.com/intel/llvm/pull/5430)**

### CODE REVIEW

**Review by againull — DISMISSED** [review]

**Comment by denis-kabanov** [comment]
Jenkins/pre-ci-windows failed due to unrelated changes, tracker created.

**Comment by againull** [comment]
@denis-kabanov Could you please resolve conflicts.

**Comment by denis-kabanov** [comment]
> @denis-kabanov Could you please resolve conflicts.

I'm not sure how to resolve these conflicts. 
The purpose of this PR was to expect an error when checking ".has(aspect::atomic64)" on the hip backend, but with new [vision](https://github.com/intel/llvm-test-suite/pull/534/files) of atomic operations tests, XFAIL may affect more tests than I thought (related to hip backend), not just tests for 64-bit operations.

**Comment by denis-kabanov** [comment]
The failure of "KernelAndProgram/kernel-bundle-merge-options-env.cpp" test is unrelated to this PR.

**Comment by denis-kabanov** [comment]
@againull, friendly ping.

**Review by againull — APPROVED** [review]

**Review by npmiller — APPROVED** [review]

**Review by jchlanda — APPROVED** [review]

**Pull request merged**
