### PR TITLE
[SYCL] use per_kernel split mode for the test SYCL/SubGroupMask/GroupSize.cpp

### PR DESCRIPTION
**Pull request by myler**

### CODE REVIEW

**Comment by myler** [comment]
Tagging @AlexeySachkov 
Automatic split based on reqd-sub-group-size is not available yet, this PR is to add `-fsycl-device-code-split=per_kernel`

**Review by AlexeySachkov — APPROVED** [review]

**Comment by myler** [comment]
pre-ci-windows testing got massive failures:
```
[2022-12-25T17:01:21.615Z] Testing Time: 1786.16s
[2022-12-25T17:01:21.615Z]   Unsupported      : 455
[2022-12-25T17:01:21.615Z]   Passed           :  62
[2022-12-25T17:01:21.615Z]   Expectedly Failed:  11
[2022-12-25T17:01:21.615Z]   Failed           : 606
```
pre-ci-linux testing failed at `Check-env Step`

**Comment by myler** [comment]
Unrelated failure
```
[2022-12-27T01:43:38.880Z]   SYCL :: Config/select_device.cpp
```

**Comment by myler** [comment]
Unrelated failure
```
[2023-01-03T01:29:18.896Z]   SYCL :: Config/select_device.cpp
```
```
[2023-01-03T01:54:33.809Z] Failed Tests (3):
[2023-01-03T01:54:33.809Z]   SYCL :: Config/select_device.cpp
[2023-01-03T01:54:33.809Z]   SYCL :: DeviceArchitecture/device_architecture.cpp
[2023-01-03T01:54:33.809Z]   SYCL :: SubGroupMask/Basic.cpp
```

This PR related test is passed.
```
[2023-01-03T01:51:42.581Z] PASS: SYCL :: SubGroupMask/GroupSize.cpp (1067 of 1133)
```
```
[2023-01-03T01:27:37.293Z] PASS: SYCL :: SubGroupMask/GroupSize.cpp (1067 of 1133)
```
@intel/llvm-reviewers-runtime @Pennycook may I ask you to merge this PR?

**Review by Pennycook — APPROVED** [review]
I can't merge, but changes LGTM.

**Pull request merged**
