### PR TITLE
[SYCL][Matrix] Minor corrections to the matrix tests

### PR DESCRIPTION
**Pull request by dkhaldi**

### CODE REVIEW

**Review by dm-vodopyanov — APPROVED** [review]
Massive test failures are unrelated to this patch, approved.

**Review by yubingex007-a11y — APPROVED** [review]

**Comment by dkhaldi** [comment]
@dm-vodopyanov, can you please help merge?

**Comment by dkhaldi** [comment]
ping? https://github.com/orgs/intel/teams/llvm-reviewers-runtime

**Comment by againull** [comment]
Only failure: SYCL :: SubGroupMask/Basic.cpp
is known and tracked.

**Pull request merged**
