### PR TITLE
[SYCL] Re-enable tests

### PR DESCRIPTION
**Pull request by s-kanaev**
The tests should start working fine when https://github.com/intel/llvm/pull/5282 is merged

### CODE REVIEW

**Comment by s-kanaev** [comment]
Failure in `Plugin/level_zero_batch_barrier.cpp` isn't related to this patch.

**Review by bader — APPROVED** [review]

**Comment by bader** [comment]
> Failure in `Plugin/level_zero_batch_barrier.cpp` isn't related to this patch.

Please, file a bug report.

**Review by smaslov-intel — APPROVED** [review]

**Comment by s-kanaev** [comment]
> Please, file a bug report.

Filed.

**Comment by s-kanaev** [comment]
Closing due fix in intel/llvm is about to be reverted in https://github.com/intel/llvm/pull/5433

**Pull request closed without merging**
