### PR TITLE
[SYCL] Disable some tests due to sporadic failure

### PR DESCRIPTION
**Pull request by denis-kabanov**
Disable SubGroup/load_store.cpp, SubGroup/reduce_spirv13.cpp, SubGroup/scan.cpp, SubGroup/scan_fp16.cpp,  SubGroup/scan_fp64.cpp, SubGroup/scan_spirv13.cpp due to Jenkins testing failure on unrelated commit.

### CODE REVIEW

**Review by AlexeySachkov — APPROVED** [review]
Would be good to have a link to the PR where it was reproduced

**Comment by denis-kabanov** [comment]
https://github.com/intel/llvm/pull/4366

**Comment by vladimirlaz** [comment]
The problem was seen only once. I have never seen that these tests are failing. It looks more like an infra issue.

**Comment by vladimirlaz** [comment]
Convert to draft to avoid accidental merge.

**Comment by vladimirlaz** [comment]
@denis-kabanov I was able to reproduce the problem without any change. Could you please created the ticket for the issue?

**Review by vladimirlaz — APPROVED** [review]

**Comment by denis-kabanov** [comment]
@vladimirlaz I have already created a ticket.

**Comment by vladimirlaz** [comment]
the tests are not failing for a while. closing the PR

**Pull request closed without merging**
