### PR TITLE
[SYCL] Add an OpenCL function caching issue workaround to get_backend

### PR DESCRIPTION
**Pull request by sergey-semenov**
There is an issue with extension function pointer caching in OpenCL
plugin: each extension function call helper keeps a pi_context-to-fptr
map cache, however, these maps aren't cleaned up on context release. This
can lead to the following situation:
- Context A is created
- An extension function is called in context A
- Context A is destroyed
- A new context B is created, which happens to have the same pi_context
handle
- The cached function is called for context B

If these two contexts have different platforms (like in get_backend
test), this will lead to an error. This patch removes the use of USM
functions from the test to circumvent this issue and reenable
get_backend API testing.

### CODE REVIEW

**Comment by sergey-semenov** [comment]
It seems that clang-format crashes because of the deletion of the first line in the file. If I recall correctly, this is a known problem.

**Review by steffenlarsen — APPROVED** [review]
As a work-around this looks good to me. Should we have a comment about it being a work-around or should we keep it after the problem has been fixed and let another - more specialized - test handle the testing?

**Comment by sergey-semenov** [comment]
Superseded by https://github.com/intel/llvm-test-suite/pull/745 & https://github.com/intel/llvm/pull/5282

**Comment by vladimirlaz** [comment]
@s-kanaev, @sergey-semenov do we need this PR? If so could you please address the CI issue?

**Comment by vladimirlaz** [comment]
@sergey-semenov, @s-kanaev, do we need this PR?

**Comment by s-kanaev** [comment]
Yes. This PR is needed. I'll handle CI failures.

**Comment by vladimirlaz** [comment]
Moving to Draft until CI failure are fixed

**Pull request closed without merging**
