### PR TITLE
[SYCL][CUDA] Fix kernel bundle related tests

### PR DESCRIPTION
**Pull request by t4c1**
Fixed kernel bundle related tests. 

The following tests were just missing SYCL triple in the compile commands:
KernelAndProgram/kernel-bundle-merge-options.cpp
KernelAndProgram/kernel-bundle-merge-options-env.cpp
KernelAndProgram/multiple-kernel-linking.cpp

The following tests are checking that compilation errors are reported during runtime, but for CUDA and HIP these are actually reported at compile time. So these were marked as unsupported and a comment was added mentioning that:
KernelAndProgram/cache-build-result.cpp
KernelAndProgram/build-log.cpp
KernelAndProgram/undefined-symbol.cpp

### CODE REVIEW

**Comment by aelovikov-intel** [comment]
> but for CUDA and HIP these are actually reported at compile time

Is there an easy way to modify the code to delay it till runtime for those platforms as well?

**Comment by t4c1** [comment]
Delaying an error message would only simplify testing. For end users it does not really make sense. It is in general best if errors are reported as soon as they occur.

**Comment by aelovikov-intel** [comment]
I meant modifying the test, not the implementation.

**Comment by t4c1** [comment]
I don't see how we could change that in the test.

**Review by aelovikov-intel — APPROVED** [review]

**Pull request merged**
