### PR TITLE
[SYCL] Disables reduction_big_data test due to flaky failures

### PR DESCRIPTION
**Pull request by KseniyaTikhomirova**
Observed flaky failures with unrelated changes

### CODE REVIEW

**Comment by KseniyaTikhomirova** [comment]
failure is observed here https://github.com/intel/llvm/pull/5349

**Comment by KseniyaTikhomirova** [comment]
@v-klochkov , @intel/llvm-reviewers-runtime, could you please review?

**Review by s-kanaev — APPROVED** [review]
LGTM

**Comment by KseniyaTikhomirova** [comment]
few notes about pre-commit checks:

failed checks there is caused by WIN failures (probably driver update) and [SYCL] Remove broken atomic_memory_order* tests #783

**Review by vladimirlaz — APPROVED** [review]

**Review by vladimirlaz — APPROVED** [review]

**Pull request merged**
