### PR TITLE
[SYCL][ESIMD][EMU] LSC support bringup

### PR DESCRIPTION
**Pull request by dongkyunahn-intel**

### CODE REVIEW

**Comment by kbobrovs** [comment]
The fact that this PR passed means that the tests were not actually run, as they could not yet pass on the emulator.
Please:
1) Make sure ESIMD emulator testing is on in CI
2) re-test it with the https://github.com/intel/llvm/pull/6099

**Comment by dongkyunahn-intel** [comment]
@pvchupin , would you check if ESIMD_EMULATOR backend is tested during Check-in tests for intel/llvm-test-suite? It looks like not.

**Comment by pvchupin** [comment]
/verify with /verify with https://github.com/intel/llvm/pull/6099

**Comment by pvchupin** [comment]
I don't think it's tested. Not sure if we have capacity to extend testing now.

**Comment by dongkyunahn-intel** [comment]
> I don't think it's tested. Not sure if we have capacity to extend testing now.

I think I had an e-mail conversation with @vladimirlaz for this issue before. I'll forward you the message if I find it.

**Comment by dongkyunahn-intel** [comment]
LSC-Atomic support for ESIMD_EMULATOR is under review : https://github.com/intel/llvm/pull/6588

**Comment by v-klochkov** [comment]
> I don't think it's tested. Not sure if we have capacity to extend testing now.

Can such testing be run by request? Something line (/verify with emulator)?

**Comment by dongkyunahn-intel** [comment]
Unrelated failure
Jenkins/pre-ci-linux
```
OpenCL
[2022-08-15T23:36:59.054Z] Failed Tests (1):
[2022-08-15T23:36:59.054Z]   SYCL :: Basic/queue/release.cpp
```
Jenkins/pre-ci-logs
(Not accessible)

**Review by kbobrovs — APPROVED** [review]
LGTM. Good to see so many tests are enabled for the emulator.
But, to be on the safe side, please retest with the latest compiler, as I merged https://github.com/intel/llvm/pull/6629 which modifies lsc atomics.

**Comment by dongkyunahn-intel** [comment]
> LGTM. Good to see so many tests are enabled for the emulator. But, to be on the safe side, please retest with the latest compiler, as I merged [intel/llvm#6629](https://github.com/intel/llvm/pull/6629) which modifies lsc atomics.

The test passes with sycl branch of intel/llvm containing the change set from PR#6629.

**Pull request merged**
