### PR TITLE
[SYCL] E2E test for Level Zero device-scope events

### PR DESCRIPTION
**Pull request by smaslov-intel**
Test for https://github.com/intel/llvm/pull/4534
Signed-off-by: Sergey V Maslov <sergey.v.maslov@intel.com>

### CODE REVIEW

**Comment by smaslov-intel** [comment]
@vladimirlaz : any idea how to fix the "get_latest_nightly" on Windows testing?

**Comment by vladimirlaz** [comment]
> @vladimirlaz : any idea how to fix the "get_latest_nightly" on Windows testing?

@smaslov-intel, this is infra issue. You can restart the test.

**Comment by smaslov-intel** [comment]
> > @vladimirlaz : any idea how to fix the "get_latest_nightly" on Windows testing?
> 
> @smaslov-intel, this is infra issue. You can restart the test.

Already tried restart yesterday, but can try again.

**Comment by vladimirlaz** [comment]
> > > @vladimirlaz : any idea how to fix the "get_latest_nightly" on Windows testing?
> > 
> > 
> > @smaslov-intel, this is infra issue. You can restart the test.
> 
> Already tried restart yesterday, but can try again.

It looks like there is CI: issue I have just reported it

**Comment by vladimirlaz** [comment]
failures are caused because compiler nightly misses https://github.com/intel/llvm/pull/4230 and can be ignored

**Review by againull — APPROVED** [review]

**Pull request merged**
