### PR TITLE
[SYCL] Update get_profiling_info() test

### PR DESCRIPTION
**Pull request by raaiq1**
Updated test to compliment https://github.com/intel/llvm/pull/6476 .

### CODE REVIEW

**Comment by raaiq1** [comment]
\verify with https://github.com/intel/llvm/pull/6476

**Review by againull — APPROVED** [review]

**Comment by againull** [comment]
\verify with https://github.com/intel/llvm/pull/6476

**Comment by raaiq1** [comment]
@intel/llvm-gatekeepers ping to merge commit

**Pull request merged**
