### PR TITLE
[SYCL] Add tests for select with bool argument

### PR DESCRIPTION
**Pull request by Pennycook**
Tests https://github.com/intel/llvm/pull/6000.

### CODE REVIEW

**Review by againull — APPROVED** [review]

**Comment by cperkinsintel** [comment]
Hmm. We updated the main llvm-test-suite to disable two problematic tests that are inexplicably failing on Linux but only on the Jenkins machines.   Now this passes on Linux (yay!). But on Windows we see:
```Unexpectedly Passed Tests (1):
[2022-04-14T00:59:16.625Z]   SYCL :: KernelAndProgram/undefined-symbol.cpp
```




Update: The unexpectedly passing/failing `undefined-symbol.cpp` has been resolved with the completion of the GPU driver uplift. Going to re-run the test, s.b. fine.

**Comment by againull** [comment]
Failures:

[2023-01-04T09:08:37.029Z]   SYCL :: Config/select_device.cpp
[2023-01-04T09:08:37.029Z]   SYCL :: SubGroupMask/Basic.cpp

are known and tracked.

**Pull request merged**
