### PR TITLE
[SYCL] [FPGA] Modifying fpga_pipes emulator test

### PR DESCRIPTION
**Pull request by tyoungsc**
Modifying the fpga_pipes.cpp test to validate the changes made in [intel/llvm#5471](https://github.com/intel/llvm/pull/5471).

The corresponding SYCL PR: [intel/llvm#5471](https://github.com/intel/llvm/pull/5471)

### CODE REVIEW

**Review by mlychkov — DISMISSED** [review]

**Review by MrSidims — DISMISSED** [review]

**Review by alexbatashev — DISMISSED** [review]

**Review by vladimirlaz — CHANGES_REQUESTED** [review]
It looks like the updated test is failing in CI with the latest compiler.
@tyoungsc , could you please fix the issue?

**Comment by tyoungsc** [comment]
> It looks like the updated test is failing in CI with the latest compiler. @tyoungsc , could you please fix the issue?

Any help on finding the actual compiler error? I have been clicking through links to try and find it with no luck. All I have right now is:

```
[](http://llvm-ci-test2.intel.com:8080/blue/organizations/jenkins/SYCL_CI%2Fintel%2FLin%2FLLVM_Test_Suite/detail/LLVM_Test_Suite/335/pipeline#step-287-log-950)[](http://llvm-ci-test2.intel.com:8080/blue/organizations/jenkins/SYCL_CI%2Fintel%2FLin%2FLLVM_Test_Suite/detail/LLVM_Test_Suite/335/pipeline#step-287-log-951)[](http://llvm-ci-test2.intel.com:8080/blue/organizations/jenkins/SYCL_CI%2Fintel%2FLin%2FLLVM_Test_Suite/detail/LLVM_Test_Suite/335/pipeline#step-287-log-952)[](http://llvm-ci-test2.intel.com:8080/blue/organizations/jenkins/SYCL_CI%2Fintel%2FLin%2FLLVM_Test_Suite/detail/LLVM_Test_Suite/335/pipeline#step-287-log-953)[](http://llvm-ci-test2.intel.com:8080/blue/organizations/jenkins/SYCL_CI%2Fintel%2FLin%2FLLVM_Test_Suite/detail/LLVM_Test_Suite/335/pipeline#step-287-log-954)[](http://llvm-ci-test2.intel.com:8080/blue/organizations/jenkins/SYCL_CI%2Fintel%2FLin%2FLLVM_Test_Suite/detail/LLVM_Test_Suite/335/pipeline#step-287-log-955)[](http://llvm-ci-test2.intel.com:8080/blue/organizations/jenkins/SYCL_CI%2Fintel%2FLin%2FLLVM_Test_Suite/detail/LLVM_Test_Suite/335/pipeline#step-287-log-956)[](http://llvm-ci-test2.intel.com:8080/blue/organizations/jenkins/SYCL_CI%2Fintel%2FLin%2FLLVM_Test_Suite/detail/LLVM_Test_Suite/335/pipeline#step-287-log-957)[](http://llvm-ci-test2.intel.com:8080/blue/organizations/jenkins/SYCL_CI%2Fintel%2FLin%2FLLVM_Test_Suite/detail/LLVM_Test_Suite/335/pipeline#step-287-log-958)[](http://llvm-ci-test2.intel.com:8080/blue/organizations/jenkins/SYCL_CI%2Fintel%2FLin%2FLLVM_Test_Suite/detail/LLVM_Test_Suite/335/pipeline#step-287-log-959)[](http://llvm-ci-test2.intel.com:8080/blue/organizations/jenkins/SYCL_CI%2Fintel%2FLin%2FLLVM_Test_Suite/detail/LLVM_Test_Suite/335/pipeline#step-287-log-960)[](http://llvm-ci-test2.intel.com:8080/blue/organizations/jenkins/SYCL_CI%2Fintel%2FLin%2FLLVM_Test_Suite/detail/LLVM_Test_Suite/335/pipeline#step-287-log-961)[2022-03-03T13:55:47.481Z] 

[2022-03-03T13:55:47.481Z] 3 warning(s) in tests

[2022-03-03T13:55:47.481Z] ********************

[2022-03-03T13:55:47.481Z] Failed Tests (1):

[2022-03-03T13:55:47.481Z]   SYCL :: Basic/fpga_tests/fpga_pipes.cpp

[2022-03-03T13:55:47.481Z] 

[2022-03-03T13:55:47.481Z] 

[2022-03-03T13:55:47.481Z] Testing Time: 2152.33s

[2022-03-03T13:55:47.481Z]   Unsupported      : 184

[2022-03-03T13:55:47.481Z]   Passed           : 604

[2022-03-03T13:55:47.481Z]   Expectedly Failed:  14

[2022-03-03T13:55:47.481Z]   Failed           :   1

[2022-03-03T13:55:47.481Z] [2022-03-03 13:55:44,206] test.main INFO: ['python3', '/netbatch/donb1987220_00/runDir/jenkins-dir/workspace/SYCL_CI/intel/Lin/LLVM_Test_Suite/llvm.obj/bin/llvm-lit', '-j', '6', '-v', '/netbatch/donb1987220_00/runDir/jenkins-dir/workspace/SYCL_CI/intel/Lin/LLVM_Test_Suite/build']
```

**Comment by mlychkov** [comment]
@tyoungsc The failed test log is the following:
```
FAIL: SYCL :: Basic/fpga_tests/fpga_pipes.cpp (132 of 809)
[2022-03-16T05:56:35.057Z] ******************** TEST 'SYCL :: Basic/fpga_tests/fpga_pipes.cpp' FAILED ********************
[2022-03-16T05:56:35.057Z] Script:
[2022-03-16T05:56:35.057Z] --
[2022-03-16T05:56:35.057Z] : 'RUN: at line 1';    /runDir/jenkins-dir/workspace/LLVM-Test-Suite-CI-TMP/LLVM-Test-Suite-CI-Linux/llvm.obj/bin/clang++      -fsycl /runDir/jenkins-dir/workspace/LLVM-Test-Suite-CI-TMP/LLVM-Test-Suite-CI-Linux/llvm-test-suite/SYCL/Basic/fpga_tests/fpga_pipes.cpp -o /runDir/jenkins-dir/workspace/LLVM-Test-Suite-CI-TMP/LLVM-Test-Suite-CI-Linux/build/SYCL/Basic/fpga_tests/Output/fpga_pipes.cpp.tmp.out
[2022-03-16T05:56:35.057Z] : 'RUN: at line 3';   true /runDir/jenkins-dir/workspace/LLVM-Test-Suite-CI-TMP/LLVM-Test-Suite-CI-Linux/build/SYCL/Basic/fpga_tests/Output/fpga_pipes.cpp.tmp.out
[2022-03-16T05:56:35.057Z] : 'RUN: at line 4';    env SYCL_DEVICE_FILTER=ext_oneapi_level_zero:gpu,host  /runDir/jenkins-dir/workspace/LLVM-Test-Suite-CI-TMP/LLVM-Test-Suite-CI-Linux/build/SYCL/Basic/fpga_tests/Output/fpga_pipes.cpp.tmp.out
[2022-03-16T05:56:35.057Z] : 'RUN: at line 5';   true /runDir/jenkins-dir/workspace/LLVM-Test-Suite-CI-TMP/LLVM-Test-Suite-CI-Linux/build/SYCL/Basic/fpga_tests/Output/fpga_pipes.cpp.tmp.out
[2022-03-16T05:56:35.057Z] --
[2022-03-16T05:56:35.057Z] Exit Code: 1
[2022-03-16T05:56:35.057Z] 
[2022-03-16T05:56:35.057Z] Command Output (stdout):
[2022-03-16T05:56:35.057Z] --
[2022-03-16T05:56:35.057Z] $ ":" "RUN: at line 1"
[2022-03-16T05:56:35.057Z] note: command had no output on stdout or stderr
[2022-03-16T05:56:35.057Z] $ "/runDir/jenkins-dir/workspace/LLVM-Test-Suite-CI-TMP/LLVM-Test-Suite-CI-Linux/llvm.obj/bin/clang++" "-fsycl" "/runDir/jenkins-dir/workspace/LLVM-Test-Suite-CI-TMP/LLVM-Test-Suite-CI-Linux/llvm-test-suite/SYCL/Basic/fpga_tests/fpga_pipes.cpp" "-o" "/runDir/jenkins-dir/workspace/LLVM-Test-Suite-CI-TMP/LLVM-Test-Suite-CI-Linux/build/SYCL/Basic/fpga_tests/Output/fpga_pipes.cpp.tmp.out"
[2022-03-16T05:56:35.057Z] # command stderr:
[2022-03-16T05:56:35.057Z] /runDir/jenkins-dir/workspace/LLVM-Test-Suite-CI-TMP/LLVM-Test-Suite-CI-Linux/llvm-test-suite/SYCL/Basic/fpga_tests/fpga_pipes.cpp:36:30: error: 'PipeMulNb' is not a class, namespace, or enumeration
[2022-03-16T05:56:35.057Z] static_assert(std::is_same_v<PipeMulNb::value_type, int>);
[2022-03-16T05:56:35.057Z]                              ^
[2022-03-16T05:56:35.057Z] /runDir/jenkins-dir/workspace/LLVM-Test-Suite-CI-TMP/LLVM-Test-Suite-CI-Linux/llvm-test-suite/SYCL/Basic/fpga_tests/fpga_pipes.cpp:35:1: note: 'PipeMulNb' declared here
[2022-03-16T05:56:35.057Z] using PipeMulNb = cl::sycl::ext::intel::pipe<class templ_nb_pipe<N>, int>;
[2022-03-16T05:56:35.057Z] ^
[2022-03-16T05:56:35.057Z] /runDir/jenkins-dir/workspace/LLVM-Test-Suite-CI-TMP/LLVM-Test-Suite-CI-Linux/llvm-test-suite/SYCL/Basic/fpga_tests/fpga_pipes.cpp:37:15: error: 'PipeMulNb' is not a class, namespace, or enumeration
[2022-03-16T05:56:35.057Z] static_assert(PipeMulNb::min_capacity == 0);
[2022-03-16T05:56:35.057Z]               ^
[2022-03-16T05:56:35.057Z] /runDir/jenkins-dir/workspace/LLVM-Test-Suite-CI-TMP/LLVM-Test-Suite-CI-Linux/llvm-test-suite/SYCL/Basic/fpga_tests/fpga_pipes.cpp:35:1: note: 'PipeMulNb' declared here
[2022-03-16T05:56:35.057Z] using PipeMulNb = cl::sycl::ext::intel::pipe<class templ_nb_pipe<N>, int>;
[2022-03-16T05:56:35.057Z] ^
[2022-03-16T05:56:35.057Z] /runDir/jenkins-dir/workspace/LLVM-Test-Suite-CI-TMP/LLVM-Test-Suite-CI-Linux/llvm-test-suite/SYCL/Basic/fpga_tests/fpga_pipes.cpp:53:30: error: 'PipeMulBl' is not a class, namespace, or enumeration
[2022-03-16T05:56:35.057Z] static_assert(std::is_same_v<PipeMulBl::value_type, int>);
[2022-03-16T05:56:35.057Z]                              ^
[2022-03-16T05:56:35.057Z] /runDir/jenkins-dir/workspace/LLVM-Test-Suite-CI-TMP/LLVM-Test-Suite-CI-Linux/llvm-test-suite/SYCL/Basic/fpga_tests/fpga_pipes.cpp:52:1: note: 'PipeMulBl' declared here
[2022-03-16T05:56:35.057Z] using PipeMulBl = cl::sycl::ext::intel::pipe<class templ_bl_pipe<N>, int>;
[2022-03-16T05:56:35.057Z] ^
[2022-03-16T05:56:35.057Z] /runDir/jenkins-dir/workspace/LLVM-Test-Suite-CI-TMP/LLVM-Test-Suite-CI-Linux/llvm-test-suite/SYCL/Basic/fpga_tests/fpga_pipes.cpp:54:15: error: 'PipeMulBl' is not a class, namespace, or enumeration
[2022-03-16T05:56:35.057Z] static_assert(PipeMulBl::min_capacity == 0);
[2022-03-16T05:56:35.057Z]               ^
[2022-03-16T05:56:35.058Z] /runDir/jenkins-dir/workspace/LLVM-Test-Suite-CI-TMP/LLVM-Test-Suite-CI-Linux/llvm-test-suite/SYCL/Basic/fpga_tests/fpga_pipes.cpp:52:1: note: 'PipeMulBl' declared here
[2022-03-16T05:56:35.058Z] using PipeMulBl = cl::sycl::ext::intel::pipe<class templ_bl_pipe<N>, int>;
[2022-03-16T05:56:35.058Z] ^
[2022-03-16T05:56:35.058Z] /runDir/jenkins-dir/workspace/LLVM-Test-Suite-CI-TMP/LLVM-Test-Suite-CI-Linux/llvm-test-suite/SYCL/Basic/fpga_tests/fpga_pipes.cpp:66:32: error: template argument for template type parameter must be a type; did you forget 'typename'?
[2022-03-16T05:56:35.058Z]   static_assert(std::is_same_v<Pipe::value_type, int>);
[2022-03-16T05:56:35.058Z]                                ^
[2022-03-16T05:56:35.058Z]                                typename 
[2022-03-16T05:56:35.058Z] /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/type_traits:2995:20: note: template parameter is declared here
[2022-03-16T05:56:35.058Z] template <typename _Tp, typename _Up>
[2022-03-16T05:56:35.058Z]                    ^
[2022-03-16T05:56:35.058Z] /runDir/jenkins-dir/workspace/LLVM-Test-Suite-CI-TMP/LLVM-Test-Suite-CI-Linux/llvm-test-suite/SYCL/Basic/fpga_tests/fpga_pipes.cpp:157:32: error: template argument for template type parameter must be a type; did you forget 'typename'?
[2022-03-16T05:56:35.058Z]   static_assert(std::is_same_v<AnotherNbPipe::value_type, int>);
[2022-03-16T05:56:35.058Z]                                ^
[2022-03-16T05:56:35.058Z]                                typename 
[2022-03-16T05:56:35.058Z] /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/type_traits:2995:20: note: template parameter is declared here
[2022-03-16T05:56:35.058Z] template <typename _Tp, typename _Up>
[2022-03-16T05:56:35.058Z]                    ^
[2022-03-16T05:56:35.058Z] /runDir/jenkins-dir/workspace/LLVM-Test-Suite-CI-TMP/LLVM-Test-Suite-CI-Linux/llvm-test-suite/SYCL/Basic/fpga_tests/fpga_pipes.cpp:201:32: error: template argument for template type parameter must be a type; did you forget 'typename'?
[2022-03-16T05:56:35.058Z]   static_assert(std::is_same_v<Pipe::value_type, int>);
[2022-03-16T05:56:35.058Z]                                ^
[2022-03-16T05:56:35.058Z]                                typename 
[2022-03-16T05:56:35.058Z] /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/type_traits:2995:20: note: template parameter is declared here
[2022-03-16T05:56:35.058Z] template <typename _Tp, typename _Up>
[2022-03-16T05:56:35.058Z]                    ^
[2022-03-16T05:56:35.058Z] /runDir/jenkins-dir/workspace/LLVM-Test-Suite-CI-TMP/LLVM-Test-Suite-CI-Linux/llvm-test-suite/SYCL/Basic/fpga_tests/fpga_pipes.cpp:271:32: error: template argument for template type parameter must be a type; did you forget 'typename'?
[2022-03-16T05:56:35.058Z]   static_assert(std::is_same_v<AnotherBlPipe::value_type, int>);
[2022-03-16T05:56:35.058Z]                                ^
[2022-03-16T05:56:35.058Z]                                typename 
[2022-03-16T05:56:35.058Z] /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/type_traits:2995:20: note: template parameter is declared here
[2022-03-16T05:56:35.058Z] template <typename _Tp, typename _Up>
[2022-03-16T05:56:35.058Z]                    ^
[2022-03-16T05:56:35.058Z] 8 errors generated.
[2022-03-16T05:56:35.058Z] 
[2022-03-16T05:56:35.058Z] error: command failed with exit status: 1
[2022-03-16T05:56:35.058Z] 
[2022-03-16T05:56:35.058Z] --
[2022-03-16T05:56:35.058Z] 
[2022-03-16T05:56:35.058Z] ********************
```

**Comment by tyoungsc** [comment]
@mlychkov fixed :)

**Review by mlychkov — APPROVED** [review]

**Review by vladimirlaz — APPROVED** [review]

**Pull request merged**
