### PR TITLE
[ESIMD] Enable ESIMD tests on Windows

### PR DESCRIPTION
**Pull request by DenisBakhvalov**

### CODE REVIEW

**Comment by vladimirlaz** [comment]
Looks like conflicts need to be resolved. Other then that the PR LGTM

**Comment by DenisBakhvalov** [comment]
> Looks like conflicts need to be resolved. Other then that the PR LGTM

Conflicts resolved, but please don't merge the PR yet. I will notify you when it's ready to be merged.

**Review by kbobrovs — APPROVED** [review]

**Comment by kbobrovs** [comment]
@DenisBakhvalov - is this PR ready for merge?

**Comment by DenisBakhvalov** [comment]
> @DenisBakhvalov - is this PR ready for merge?

No, not yet. The fix that enables ESIMD on Windows is in the newer GPU driver version. We need to wait until the version will be uplifted.

**Comment by vladimirlaz** [comment]
@DenisBakhvalov  is it Ok to merge the PR? It looks like tests are passing both on Windows and Linux.

**Review by vladimirlaz — APPROVED** [review]

**Review by vladimirlaz — CHANGES_REQUESTED** [review]
@DenisBakhvalov  there are new tests to be updated (e.g. SYCL/ESIMD/regression/unused_load.cpp and SYCL/ESIMD/regression/big_const_initializer.cpp )

**Comment by DenisBakhvalov** [comment]
> @DenisBakhvalov there are new tests to be updated (e.g. SYCL/ESIMD/regression/unused_load.cpp and SYCL/ESIMD/regression/big_const_initializer.cpp )

Yes, I will update those when the PR will be ready for merging.

**Review by kbobrovs — DISMISSED** [review]

**Comment by DenisBakhvalov** [comment]
@vladimirlaz please merge this PR. It was approved earlier. Since then I only backed some changes, so I hope approvals still hold.

I would like to enable the passing tests in CI asap for Windows tracking purposes.

I'm still figuring out why I see some tests failing in CI, while locally they pass for me on a new GPU driver. I will submit a separate PR once I resolve those issues.

**Review by vladimirlaz — APPROVED** [review]

**Pull request merged**
