### PR TITLE
correct bfloat16 class namespace

### PR DESCRIPTION
**Pull request by dkhaldi**

### CODE REVIEW

**Review by rdeodhar — APPROVED** [review]
Changes look good.

**Review by yubingex007-a11y — APPROVED** [review]

**Review by rdeodhar — APPROVED** [review]
Looks good.

**Comment by yubingex007-a11y** [comment]
ping? @intel/llvm-reviewers-runtime 
please approve and merge?

**Comment by againull** [comment]
CI failures are unrelated.

**Pull request merged**
