### PR TITLE
[SYCL] test for barrier batching

### PR DESCRIPTION
**Pull request by smaslov-intel**
Compiler changes are in https://github.com/intel/llvm/pull/5328
Signed-off-by: Sergey V Maslov <sergey.v.maslov@intel.com>

### CODE REVIEW

**Comment by smaslov-intel** [comment]
> /verify with [intel/llvm#5328](https://github.com/intel/llvm/pull/5328)

@vladimirlaz : is this the right syntax? How to verify that the changes from that PR were actually applied for testing? The way the tests fail (hang) look like they are with an unmodified compiler.

**Comment by vladimirlaz** [comment]
According to http://icl-jenkins2.sc.intel.com:8080/blue/organizations/jenkins/SYCL_CI%2Fintel%2FLin%2FLLVM_Test_Suite/detail/LLVM_Test_Suite/184/pipeline/79 the correct hash is used: 82b2f3fa20b071fe6aa972bdf63e5ea76b401b60

**Comment by smaslov-intel** [comment]
> According to http://icl-jenkins2.sc.intel.com:8080/blue/organizations/jenkins/SYCL_CI%2Fintel%2FLin%2FLLVM_Test_Suite/detail/LLVM_Test_Suite/184/pipeline/79 the correct hash is used: 82b2f3fa20b071fe6aa972bdf63e5ea76b401b60

Thanks! I will study it more then.

**Comment by smaslov-intel** [comment]
> > According to http://icl-jenkins2.sc.intel.com:8080/blue/organizations/jenkins/SYCL_CI%2Fintel%2FLin%2FLLVM_Test_Suite/detail/LLVM_Test_Suite/184/pipeline/79 the correct hash is used: 82b2f3fa20b071fe6aa972bdf63e5ea76b401b60
> 
> Thanks! I will study it more then.

You link is for "Jenkins/llvm-test-suite" check and the failure there kind of makes sense.
But the fail in "Jenkins/pre-ci-linux" is not expected, and I don't see the right hash being used: http://icl-jenkins.sc.intel.com:8080/blue/organizations/jenkins/LLVM-Test-Suite-CI-TMP%2FLLVM-Test-Suite-CI-Linux/detail/LLVM-Test-Suite-CI-Linux/1536/pipeline/120

Are we only doing "Jenkins/llvm-test-suite" with an llvm PR?

**Comment by vladimirlaz** [comment]
`/verify with` affects only Jenkins/llvm-test-suite

**Comment by smaslov-intel** [comment]
> `/verify with` affects only Jenkins/llvm-test-suite

That explains it, thanks!

**Comment by smaslov-intel** [comment]
This has expectedly passed with https://github.com/intel/llvm/pull/5328.
The failures without the compiler changes are also as expected.

**Review by againull — APPROVED** [review]

**Pull request merged**
