### PR TITLE
[SYCL][CUDA] Enabled unified matrix tests

### PR DESCRIPTION
**Pull request by JackAKirk**
Tests https://github.com/intel/llvm/pull/7077

Signed-off-by: JackAKirk <jack.kirk@codeplay.com>

### CODE REVIEW

**Review by dkhaldi — APPROVED** [review]
LGTM

**Review by aelovikov-intel — APPROVED** [review]

**Comment by againull** [comment]
Failure:
SYCL :: SubGroupMask/Basic.cpp
is known and tracked.

**Pull request merged**
