### PR TITLE
[SYCL] Remove tests using sycl::program

### PR DESCRIPTION
**Pull request by KornevNikita**
According to SYCL2020 sycl::program is deprecated and should be removed.
Original patch: https://github.com/intel/llvm/pull/6666

### CODE REVIEW

**Comment by KornevNikita** [comment]
I'm not sure if we should delete these tests since they can't be compiled or just somehow turn them off.

**Comment by romanovvlad** [comment]
LGTM. @kbobrovs Could you please take a look as well?

**Comment by AlexeySachkov** [comment]
For `ESIMD` tests: I made copies which use up-to-date interfaces here: https://github.com/intel/llvm-test-suite/tree/intel/SYCL/ESIMD/spec_const
Actual tests for spec constants are present as well, so no objections from removing the outdated ones. Link to those tests: https://github.com/intel/llvm-test-suite/tree/intel/SYCL/SpecConstants/2020

**Review by kbobrovs — APPROVED** [review]
LGTM. There is no non-deprecated analog of spec_const_redefine, I filed internal tracker.

**Review by romanovvlad — APPROVED** [review]

**Pull request merged**
