### PR TITLE
[SYCL][ESIMD] Eliminated use of deprecated API

### PR DESCRIPTION
**Pull request by sndmitriev**
Signed-off-by: Sergey Dmitriev <serguei.n.dmitriev@intel.com>

### CODE REVIEW

**Comment by sndmitriev** [comment]
The following 7 tests are expected to fail until https://github.com/intel/llvm/pull/5402 is merged

```
[2022-01-28T06:58:14.054Z]   SYCL :: ESIMD/PrefixSum.cpp
[2022-01-28T06:58:14.054Z]   SYCL :: ESIMD/Prefix_Local_sum3.cpp
[2022-01-28T06:58:14.054Z]   SYCL :: ESIMD/matrix_transpose.cpp
[2022-01-28T06:58:14.054Z]   SYCL :: ESIMD/matrix_transpose2.cpp
[2022-01-28T06:58:14.054Z]   SYCL :: ESIMD/matrix_transpose_glb.cpp
[2022-01-28T06:58:14.054Z]   SYCL :: ESIMD/matrix_transpose_usm.cpp
[2022-01-28T06:58:14.054Z]   SYCL :: ESIMD/regression/dgetrf_8x8.cpp
```

These fails are unrelated to this change.

Jenkins/pre-ci-cuda
```
[2022-01-28T07:17:04.118Z]   SYCL :: AtomicRef/atomic_memory_order_acq_rel.cpp
[2022-01-28T07:17:04.118Z]   SYCL :: AtomicRef/atomic_memory_order_acq_rel_atomic64.cpp
```

Jenkins/pre-ci-windows, PI_LevelZero Step
```
[2022-01-28T07:49:00.903Z]   SYCL :: Basic/image/image_accessor_readsampler.cpp
[2022-01-28T07:49:00.903Z]   SYCL :: Basic/image/image_sample.cpp
[2022-01-28T07:49:00.904Z]   SYCL :: Sampler/normalized-clampedge-linear-float.cpp
[2022-01-28T07:49:00.904Z]   SYCL :: Sampler/normalized-clampedge-nearest.cpp
[2022-01-28T07:49:00.904Z]   SYCL :: Sampler/unnormalized-clamp-nearest.cpp
[2022-01-28T07:49:00.904Z]   SYCL :: Sampler/unnormalized-clampedge-linear-float.cpp
[2022-01-28T07:49:00.904Z]   SYCL :: Sampler/unnormalized-clampedge-nearest.cpp
```

**Review by kbobrovs — DISMISSED** [review]

**Review by kbobrovs — APPROVED** [review]

**Comment by kbobrovs** [comment]
Failures are unrelated. @vladimirlaz, @bader - could you please merge? W/o this PR the following tests are failing:
```
[2022-01-28T06:58:14.054Z]   SYCL :: ESIMD/PrefixSum.cpp
[2022-01-28T06:58:14.054Z]   SYCL :: ESIMD/Prefix_Local_sum3.cpp
[2022-01-28T06:58:14.054Z]   SYCL :: ESIMD/matrix_transpose.cpp
[2022-01-28T06:58:14.054Z]   SYCL :: ESIMD/matrix_transpose2.cpp
[2022-01-28T06:58:14.054Z]   SYCL :: ESIMD/matrix_transpose_glb.cpp
[2022-01-28T06:58:14.054Z]   SYCL :: ESIMD/matrix_transpose_usm.cpp
[2022-01-28T06:58:14.054Z]   SYCL :: ESIMD/regression/dgetrf_8x8.cpp
```

Failures from this testing:
pre-ci-windows:
```
[2022-01-30T00:02:00.706Z]   SYCL :: Basic/image/image_accessor_readsampler.cpp
[2022-01-30T00:02:00.706Z]   SYCL :: Basic/image/image_sample.cpp
[2022-01-30T00:02:00.706Z]   SYCL :: Sampler/normalized-clampedge-linear-float.cpp
[2022-01-30T00:02:00.706Z]   SYCL :: Sampler/normalized-clampedge-nearest.cpp
[2022-01-30T00:02:00.706Z]   SYCL :: Sampler/unnormalized-clamp-nearest.cpp
[2022-01-30T00:02:00.706Z]   SYCL :: Sampler/unnormalized-clampedge-linear-float.cpp
[2022-01-30T00:02:00.706Z]   SYCL :: Sampler/unnormalized-clampedge-nearest.cpp
```

pre-ci-cuda:
```
[2022-01-30T00:08:37.569Z]   SYCL :: AtomicRef/atomic_memory_order_acq_rel.cpp
[2022-01-30T00:08:37.569Z]   SYCL :: AtomicRef/atomic_memory_order_acq_rel_atomic64.cpp
```

**Pull request merged**
