### PR TITLE
[SYCL] Fix UNSUPPORTED syntax for DiscardEvents/invalid_event.cpp

### PR DESCRIPTION
**Pull request by AGindinson**
As shown by CI for #569, the unsupported combination of opencl && acc
still shows up. Attempt to fix this by using a common operator style
as a follow-up to #652.

Signed-off-by: Artem Gindinson <artem.gindinson@intel.com>

### CODE REVIEW

**Review by sergey-semenov — APPROVED** [review]

**Review by bader — CHANGES_REQUESTED** [review]
@vmaksimo, @AGindinson, @sergey-semenov, could you clarify how this (opencl && acc) disables the test?
I still see in the logs that test is executed. AFAIK, llvm-test-suite is not executed on acc in a separate invocation. Accelerator is tested as part of the OpenCL back-end validation. I think the right way to disable testing on accelerator is it remove `RUN: %ACC_RUN_PLACEHOLDER %t.out` line.

**Comment by bader** [comment]
I think we can merge this version of the patch to fix validation on HIP back-end, but someone need to verify that validation on OpenCL accelerator type of devices is disabled.

**Comment by AGindinson** [comment]
> Could you clarify how this (opencl && acc) disables the test?

I would expect this to work like https://github.com/intel/llvm-test-suite/blob/intel/SYCL/Basic/image/image_max_size.cpp#L1 does - the test does get launched, but the corresponding `RUN_PLACEHOLDER` line is not executed. I have to say I'm unsure of the exact mechanism.

**Comment by bader** [comment]
> > Could you clarify how this (opencl && acc) disables the test?
> 
> I would expect this to work like https://github.com/intel/llvm-test-suite/blob/intel/SYCL/Basic/image/image_max_size.cpp#L1 does - the test does get launched, but the corresponding `RUN_PLACEHOLDER` line is not executed. I have to say I'm unsure of the exact mechanism.

It doesn't work like this. Take a look at https://github.com/intel/llvm-test-suite/blob/intel/SYCL/lit.cfg.py#L310-L322 to learn how placeholder line work. It doesn't take into account particular test LIT commands. It uses configuration provided to the test runner script. i.e. whether `acc` was requested as a target device for llvm-test-suite.

It would work if you specify `accelerator` instead of `acc`, but it will disable the whole test, not specific RUN command (i.e. disable testing on other devices).
https://github.com/intel/llvm-test-suite/blob/intel/SYCL/lit.cfg.py#L317 - UNSUPPORTED is tested against `available_features`, which is named `accelerator`.

**Comment by bader** [comment]
> It would work if you specify accelerator instead of acc, but it will disable the whole test, not specific RUN command (i.e. disable testing on other devices).

I mean CI system here, which run tests on machines with all devices available. If we run on the system w/o FPGA runtime, UNSUPPORTED: opencl && accelerator will not disable the test.

**Comment by bader** [comment]
You can read more about how UNSUPPORTED work in llvm documentation - https://llvm.org/docs/TestingGuide.html#constraining-test-execution.

> REQUIRES and UNSUPPORTED and XFAIL all accept a comma-separated list of boolean expressions. The values in each expression may be:
> 
> * Features added to config.available_features by configuration files such as lit.cfg. String comparison of features is case-sensitive. Furthermore, a boolean expression can contain any Python regular expression enclosed in {{ }}, in which case the boolean expression is satisfied if any feature matches the regular expression. Regular expressions can appear inside an identifier, so for example he{{l+}}o would match helo, hello, helllo, and so on.
> * Substrings of the target triple (UNSUPPORTED and XFAIL only).
>
> REQUIRES enables the test if all expressions are true.
> UNSUPPORTED disables the test if any expression is true.

**Comment by bader** [comment]
Another attempt to disable the test - https://github.com/intel/llvm-test-suite/pull/671.

**Pull request merged**
