### PR TITLE
[SYCL][ESIMD] Add test on simd load constructor for fp_extra types

### PR DESCRIPTION
**Pull request by vasilytric**
Extend coverage for existing test on simd load constructor by coverage extra floating point types.
There is no changes in the tests logic.

### CODE REVIEW

**Comment by yuriykoch** [comment]
Looks like [26b43da](https://github.com/intel/llvm-test-suite/pull/797/commits/26b43da97c29a20423e16bf7f25b3922c2fcce59) should be in a separate PR, with `get_all_dimensions` renamed.

**Comment by vasilytric** [comment]
> Looks like [26b43da](https://github.com/intel/llvm-test-suite/pull/797/commits/26b43da97c29a20423e16bf7f25b3922c2fcce59) should be in a separate PR, with get_all_dimensions renamed.

@yuriykoch yes, you is right, 26b43da97c29a20423e16bf7f25b3922c2fcce59 has been reverted and these changes will be provided in a separate PR

**Comment by vasilytric** [comment]
@sndmitriev  Would you mind to take a look?

**Review by sndmitriev — DISMISSED** [review]

**Comment by vasilytric** [comment]
@kbobrovs Would you mind to merge this PR?

**Review by vladimirlaz — CHANGES_REQUESTED** [review]
@vasilytric  could you please resolve the conflict?

**Comment by vasilytric** [comment]
> @vasilytric could you please resolve the conflict?

@vladimirlaz Done. Let's wait CI result

**Comment by vasilytric** [comment]
@sndmitriev I am sorry that I request approval from you third time for this PR. But could you approve this PR?

**Review by sndmitriev — APPROVED** [review]

**Comment by vasilytric** [comment]
@kbobrovs Would you merge this PR?

**Review by kbobrovs — APPROVED** [review]

**Comment by kbobrovs** [comment]
@vladimirlaz , please approve and merge, I can't due to "1 change requested"

**Review by vladimirlaz — APPROVED** [review]

**Pull request merged**
