### PR TITLE
Update clang-offload-bundler usage

### PR DESCRIPTION
**Pull request by mdtoguchi**
The commands for clang-offload-bundler have been updated to use -output
instead of -outputs.  Update test.cpp which uses clang-offload-bundler
directly

### CODE REVIEW

**Comment by mdtoguchi** [comment]
Looks like testing picks up the nightly builds of the compilers.  The latest pulldown just occurred, so I will have to kick this off one the new changes to the bundler have landed.

**Comment by mdtoguchi** [comment]
tested with updated compiler, looks OK now.  @intel/dpcpp-tools-reviewers, could you take a look?

**Review by asudarsa — APPROVED** [review]
LGTM. Thanks

**Pull request merged**
