### PR TITLE
Set object extension based on system and not driver used

### PR DESCRIPTION
**Pull request by mdtoguchi**
Running tests with clang-cl would set the proper object extension, but
clang and clang++ on Windows would use the wrong .o extension.

### CODE REVIEW

**Comment by mdtoguchi** [comment]
Failure is not related to my change

**Comment by mdtoguchi** [comment]
restart of testing looks OK now.

**Comment by mdtoguchi** [comment]
@intel/llvm-reviewers-runtime, ping

**Review by smaslov-intel — APPROVED** [review]

**Comment by v-klochkov** [comment]
@pvchupin - Please take a look, it may require additional approval if considered backward compatibility.

**Review by v-klochkov — APPROVED** [review]

**Pull request merged**
