### PR TITLE
[SYCL] Add a test targeting internal reduction APIs

### PR DESCRIPTION
**Pull request by aelovikov-intel**
That way we can bypass strategy selection and test any of them with the same type/operation.

### CODE REVIEW

**Comment by aelovikov-intel** [comment]
I think this would make some existing tests redundant but I'm not comfortable in removing any of them yet.

**Comment by aelovikov-intel** [comment]
Failure on

SYCL :: KernelAndProgram/kernel-bundle-merge-options-env.cpp

is being tracked in internal bug report.

**Review by steffenlarsen — APPROVED** [review]
In the future I would love to see these exposed as properties so users can take control of it too, but for now I think this looks good.

**Pull request merged**
