### PR TITLE
[SYCL] Add kernel_bundle_api.cpp test

### PR DESCRIPTION
**Pull request by romanovvlad**

### CODE REVIEW

**Comment by romanovvlad** [comment]
Moving from inte/llvm repo: https://github.com/intel/llvm/pull/3824

**Comment by vladimirlaz** [comment]
@romanovvlad, could you please fix clang-format issue?

**Review by vladimirlaz — APPROVED** [review]
The test is executed only on CPU device. Is it reasonable to run on GPU and ACC devices if present?
Does kernel_bundle supports host device?

**Comment by romanovvlad** [comment]
> 
> 
> The test is executed only on CPU device. Is it reasonable to run on GPU and ACC devices if present?
> Does kernel_bundle supports host device?

Host device is not supported. Do not see a lot of value in testing more than one device.

**Pull request merged**
