### PR TITLE
[SYCL] reenabling test in anticipation of GPU uplift

### PR DESCRIPTION
**Pull request by cperkinsintel**
Pairs with https://github.com/intel/llvm/pull/6018

Signed-off-by: Chris Perkins <chris.perkins@intel.com>

### CODE REVIEW

**Review by againull — DISMISSED** [review]

**Comment by cperkinsintel** [comment]
These tests are taking forever to run. The CI check named "Jenkins/pre-ci-linux" will likely fail, that is expected. 
The CI check named "Jenkins/llvm-test-suite" is the one requested with the verify comment. If it passes (fingers crossed) then we should be good to go to merge this and then to merge the GPU uplift PR at https://github.com/intel/llvm/pull/6018  and to close the outdated uplift attempt at https://github.com/intel/llvm/pull/5995

**Comment by cperkinsintel** [comment]
ping to reviewers - this is ready to review and merge. As mentioned in the previous comment, the "Jenkins/pre-ci-linux" CI run is expected to fail and is irrelevant. The important part is that the "Jenkins/llvm-test-suite" run passed.  Once this is merged we can then approve/merge the new GPU uplift (https://github.com/intel/llvm/pull/6018)  and close the outdated one ( https://github.com/intel/llvm/pull/5995 )

**Review by steffenlarsen — APPROVED** [review]

**Comment by cperkinsintel** [comment]
ping @againull  or @pvchupin to merge this so we can get the 6018 uplift merged too and get closer to reliable testing.

**Pull request merged**
