### PR TITLE
[SYCL] Test exception throwing for unsupported kernel feature

### PR DESCRIPTION
**Pull request by KornevNikita**
sycl patch: https://github.com/intel/llvm/pull/6989

### CODE REVIEW

**Review by dm-vodopyanov — APPROVED** [review]
nit: Maybe use exception handler?

**Comment by KornevNikita** [comment]
Waiting for https://github.com/intel/llvm/pull/6982 to test

**Comment by KornevNikita** [comment]
Re-run tests

**Comment by KornevNikita** [comment]
Failure is unrelated

**Comment by KornevNikita** [comment]
@intel/llvm-gatekeepers

**Review by AlexeySachkov — CHANGES_REQUESTED** [review]
```
[2022-11-08T14:12:02.560Z] ********************

[2022-11-08T14:12:02.560Z] Failed Tests (1):

[2022-11-08T14:12:02.560Z]   SYCL :: OptionalKernelFeatures/throw-exception-for-unsupported-aspect.cpp

[2022-11-08T14:12:02.560Z] 
```
This can't be an unrelated failure. [Linux, OpenCL](http://icl-jenkins.sc.intel.com:8080/blue/organizations/jenkins/LLVM-Test-Suite-CI-TMP%2FLLVM-Test-Suite-CI-Linux/detail/LLVM-Test-Suite-CI-Linux/3659/pipeline)

**Comment by KornevNikita** [comment]
@AlexeySachkov oh, I believe it's enough to re-run tests, it was fixed in https://github.com/intel/llvm-test-suite/commit/de9a2093f63046f8246173d94556ced656c90693

**Comment by KornevNikita** [comment]
I found out that there is no support for `device_has` yet, so we see this failure. Moving to draft until `device_has` support is ready.

**Comment by KornevNikita** [comment]
Support for `device_has`: https://github.com/intel/llvm/pull/7419

**Comment by KornevNikita** [comment]
Re-run CI

**Comment by KornevNikita** [comment]
@AlexeySachkov I believe this time failures are really unrelated.

**Review by AlexeySachkov — APPROVED** [review]

**Pull request merged**
