### PR TITLE
[ESIMD] Disable several tests failed after pulldown from LLORG intel/llvm#4993

### PR DESCRIPTION
**Pull request by vmaksimo**
This change should be reverted once the tests are fixed.

### CODE REVIEW

**Comment by kbobrovs** [comment]
@vmaksimo - do you have link to test failure logs?

**Comment by vladimirlaz** [comment]
the tests on CUDA failed due to unrelated regression in compiler: intel/llvm#5008

**Review by vladimirlaz — APPROVED** [review]

**Comment by vmaksimo** [comment]
> @vmaksimo - do you have link to test failure logs?

Sure: http://llvm-ci-test2.intel.com:8080/blue/organizations/jenkins/SYCL_CI%2Fintel%2FLin%2FBasic_E2E/detail/Basic_E2E/234/pipeline

**Pull request merged**
