### PR TITLE
[SYCL] Add regression test for 0-size local accessors

### PR DESCRIPTION
**Pull request by steffenlarsen**
This tests https://github.com/intel/llvm/pull/6032.

### CODE REVIEW

**Comment by v-klochkov** [comment]
The test fails in CI. Do you expect some changes in GPU RT that would allow this test to pass?

**Comment by steffenlarsen** [comment]
> The test fails in CI. Do you expect some changes in GPU RT that would allow this test to pass?

https://github.com/intel/llvm/pull/6032 is required for this test to pass. The verification run (Jenkins/llvm-test-suite) confirms this.

**Comment by steffenlarsen** [comment]
@v-klochkov - Friendly ping.

**Review by v-klochkov — APPROVED** [review]

**Pull request merged**
