### PR TITLE
[SYCL][CUDA] Add ftz test

### PR DESCRIPTION
**Pull request by hdelan**
This should be merged once https://github.com/intel/llvm/pull/7616 is merged

### CODE REVIEW

**Comment by v-klochkov** [comment]
Please fix the 'clang-format' issues. https://github.com/intel/llvm-test-suite/actions/runs/3641476981/jobs/6147455235

**Comment by againull** [comment]
Jenkins/llvm-test-suite is tested with  compiler from ~Dec 14 (PR is old), hence resulting in multiple unrelated failures and it doesn't make sense to analyze them as they don't reproduce with up-to-date compiler. And new test is passing.

Default testing Jenkins/pre-ci-linux + Jenkins/pre-ci-windows  is clean.

**Pull request merged**
