### PR TITLE
[ESIMD] Enable more ESIMD tests on Level Zero

### PR DESCRIPTION
**Pull request by DenisBakhvalov**

### CODE REVIEW

**Review by vladimirlaz — APPROVED** [review]

**Comment by vladimirlaz** [comment]
It looks like these tests will run on CUDA BE also. I do not think it is expected.

**Comment by DenisBakhvalov** [comment]
> It looks like these tests will run on CUDA BE also. I do not think it is expected.

I see. You suggest adding `// UNSUPPORTED: cuda` in ESIMD tests, right?
I can do that in a separate PR if it's ok.

**Comment by vladimirlaz** [comment]
> > It looks like these tests will run on CUDA BE also. I do not think it is expected.
> 
> I see. You suggest adding `// UNSUPPORTED: cuda` in ESIMD tests, right?
> I can do that in a separate PR if it's ok.

I would prefer if the tests will be marked as //UNSUPPORTED: cuda in this PR.

**Comment by DenisBakhvalov** [comment]
> > > It looks like these tests will run on CUDA BE also. I do not think it is expected.
> > 
> > 
> > I see. You suggest adding `// UNSUPPORTED: cuda` in ESIMD tests, right?
> > I can do that in a separate PR if it's ok.
> 
> I would prefer if the tests will be marked as //UNSUPPORTED: cuda in this PR.

Yes, but we need this attribute in all the ESIMD tests, not just the ones mentioned in this PR.
This is why I suggest to do it in a separate PR. What do you think?

**Comment by DenisBakhvalov** [comment]
> > > > It looks like these tests will run on CUDA BE also. I do not think it is expected.
> > > 
> > > 
> > > I see. You suggest adding `// UNSUPPORTED: cuda` in ESIMD tests, right?
> > > I can do that in a separate PR if it's ok.
> > 
> > 
> > I would prefer if the tests will be marked as //UNSUPPORTED: cuda in this PR.
> 
> Yes, but we need this attribute in all the ESIMD tests, not just the ones mentioned in this PR.
> This is why I suggest to do it in a separate PR. What do you think?

I created a PR here: https://github.com/intel/llvm-test-suite/pull/80

**Review by kbobrovs — APPROVED** [review]

**Review by vladimirlaz — APPROVED** [review]

**Pull request merged**
