### PR TITLE
[LIT][L0] enable global offset support test for level_zero.

### PR DESCRIPTION
**Pull request by rbegam**
Signed-off-by: rbegam <rehana.begam@intel.com>

### CODE REVIEW

**Review by smaslov-intel — APPROVED** [review]

**Comment by rbegam** [comment]
This test depends on PR https://github.com/intel/llvm/pull/3593 and vise versa.

**Comment by vladimirlaz** [comment]
> This test depends on PR [intel/llvm#3593](https://github.com/intel/llvm/pull/3593) and vise versa.

it looks like we need to submit intel/llvm change first (CI will pass as test is skipped and the tests should be tested locally). Once next nightly is available the CI for intel/llvm-test-suite change can be restarted and change submitted

**Comment by rbegam** [comment]
@vladimirlaz I agree that this test needs to be merged after the compiler change intel/llvm#3593. But that PR is actually failing in pre-commit checks s the test is unexpectedly passing:
http://icl-jenkins.sc.intel.com:8080/blue/organizations/jenkins/SYCL_CI%2Fintel%2FLin%2FLLVM_Test_Suite/detail/LLVM_Test_Suite/4259/pipeline

Unexpectedly Passed Tests (1):
    SYCL :: Basic/parallel_for_indexers.cpp

**Review by vladimirlaz — APPROVED** [review]

**Comment by vladimirlaz** [comment]
The test failures are expected and need intel/llvm#3593 to be fixed

**Pull request merged**
