### PR TITLE
[ESIMD] E2E test for simd_view copy and move ctors

### PR DESCRIPTION
**Pull request by DenisBakhvalov**

### CODE REVIEW

**Comment by kychendev** [comment]
Looks good - lease double check code quality before commit.

**Review by kychendev — APPROVED** [review]

**Comment by DenisBakhvalov** [comment]
> Looks good - lease double check code quality before commit.

Compared SPV files for all the ESIMD tests that we have in a suite. Found only one mismatch but the difference is insignificant.

**Comment by kychendev** [comment]
> > Looks good - lease double check code quality before commit.
> 
> Compared SPV files for all the ESIMD tests that we have in a suite. Found only one mismatch but the difference is insignificant.

Sounds good. Thanks for checking.

**Comment by DenisBakhvalov** [comment]
I believe windows CI is failing on unrelated tests, which are covered by https://github.com/intel/llvm-test-suite/pull/411
@vladimirlaz, please merge.

**Pull request merged**
