### PR TITLE
[LIT][L0] test for multi-CCS support in level_zero.

### PR DESCRIPTION
**Pull request by rbegam**
Signed-off-by: rehana begam <rehana.begam@intel.com>

### CODE REVIEW

**Comment by rbegam** [comment]
This test is associated with PR https://github.com/intel/llvm/pull/4038. The test is suppose to fail until the PR is merged.

**Review by vladimirlaz — DISMISSED** [review]

**Comment by rbegam** [comment]
The cuda fail is for the following test, not part of this PR:

   Failed Tests (1):
      SYCL :: Regression/unoptimized_stream.cpp

**Comment by rbegam** [comment]
ping @vladimirlaz

**Comment by rbegam** [comment]
ping @smaslov-intel @vladimirlaz

**Review by smaslov-intel — APPROVED** [review]

**Pull request merged**
