### PR TITLE
[SYCL][ESIMD][EMU] ESIMD test updates for esimd_emulator backend

### PR DESCRIPTION
**Pull request by dongkyunahn-intel**
- Reducing number of iterations / Limiting matrix size in order to avoid timeout failure
- Removing 'XFAIL' from passing tests

### CODE REVIEW

**Review by kbobrovs — DISMISSED** [review]
LGTM. Good to see so many new tests will run on emulator!

**Review by kychendev — DISMISSED** [review]

**Comment by dongkyunahn-intel** [comment]
@vladimirlaz , would you merge this PR? It is required for enabling ESIMD_EMULATOR in intel/llvm.

https://github.com/intel/llvm/pull/5677

**Comment by dongkyunahn-intel** [comment]
@vladimirlaz , I found out one test needs to be updated. I'll let you know when this PR is ready for PR. Sorry for confusion.

**Comment by dongkyunahn-intel** [comment]
@kbobrovs , @kychendev , would you re-approve this PR? One test (`variable_gather_mask.cpp`) needs to be marked `XFAIL` for esimd_emulator backend as the feature support is still under review.

**Review by kychendev — APPROVED** [review]

**Review by kbobrovs — APPROVED** [review]

**Pull request merged**
