### PR TITLE
[SYCL][Fusion] Pass -O2 flag to tests performing argument promotion

### PR DESCRIPTION
**Pull request by victor-eds**
No promotion will take place if -O0 is passed, so add this flag to override options possibly disrupting tests results.

### CODE REVIEW

**Review by sommerlukas — APPROVED** [review]
LGTM.

**Comment by steffenlarsen** [comment]
We recently saw cases where `-O` flags were ignored on Windows because the test-suite uses `clang-cl`. As such I worry this only avoid the problem on Linux. A more stable solution could be to introduce new LIT variables picking `-O2` or `/O2` depending on the target.

**Comment by sommerlukas** [comment]
> We recently saw cases where `-O` flags were ignored on Windows because the test-suite uses `clang-cl`. As such I worry this only avoid the problem on Linux. A more stable solution could be to introduce new LIT variables picking `-O2` or `/O2` depending on the target.

Note that fusion is currently only supported on Linux. On Windows, the LIT configuration feature `fusion` is not available, so all the tests with the `-O` flag should be marked unsupported by the `REQUIRES: fusion` clause.

**Review by steffenlarsen — APPROVED** [review]
> Note that fusion is currently only supported on Linux. On Windows, the LIT configuration feature fusion is not available, so all the tests with the -O flag should be marked unsupported by the REQUIRES: fusion clause.

Point taken! In that case, I am okay with this. If Windows support is added in the future, please keep my previous comment in mind. 😄

**Pull request merged**
