### PR TITLE
[SYCL][CUDA] Re-enable tests that were marked as UNSUPPORTED for the CUDA backend

### PR DESCRIPTION
**Pull request by jle-quel**
This PR re-enables the test marked as UNSUPPORTED for the CUDA backend.

As a result of these tests ran to update this issue: https://github.com/intel/llvm-test-suite/issues/249; Specifically, the part which mentions the tests that passed but are marked as unsupported;

I'm proposing this PR to re-enable them.

### CODE REVIEW

**Review by Pennycook — APPROVED** [review]
Sub-group changes LGTM.

**Comment by jle-quel** [comment]
I wanted to check in on the status of this PR. It has passed all tests, and I believe it is ready to be merged. Is there any blocker preventing this from being reviewed or merged?

**Comment by jle-quel** [comment]
@bader

**Comment by bader** [comment]
> I wanted to check in on the status of this PR. It has passed all tests, and I believe it is ready to be merged. Is there any blocker preventing this from being reviewed or merged?

Code review from @intel/llvm-reviewers-runtime team is missing.

**Review by bader — APPROVED** [review]

**Comment by jle-quel** [comment]
We can merge this PR now; I'm not authorized to do so, could you @bader, please?

**Review by steffenlarsen — APPROVED** [review]
Great!

**Pull request merged**
