### PR TITLE
[SYCL] Enable shuffle tests on HIP AMD.

### PR DESCRIPTION
**Pull request by jchlanda**
Even though `gfx908` and `gfx906` support halfs, libspirv is currently
built with `tahiti` as the target CPU, which means that clang rejects
AMD built-ins using halfs, for that reason half support has to stay
disabled.

### CODE REVIEW

**Comment by jchlanda** [comment]
Corresponding work in llvm repo: https://github.com/intel/llvm/pull/4664

**Comment by Pennycook** [comment]
> Half test is still xfail as neither gfx908 nor gfx906 supports it.

Sorry if this is a silly question -- is this something you could work around by forwarding to an integer shuffle, or does compilation for these platforms fail as soon as they see a half type in a kernel?

**Comment by npmiller** [comment]
> > Half test is still xfail as neither gfx908 nor gfx906 supports it.
> 
> Sorry if this is a silly question -- is this something you could work around by forwarding to an integer shuffle, or does compilation for these platforms fail as soon as they see a half type in a kernel?

To expand a bit on that `gfx906` and `gfx908` actually do support half as far as I understand it, the issue is that libspirv is currently built with `tahiti` as the target CPU, which means that clang rejects AMD built-ins using halfs, as `tahiti` doesn't support them.

This is definitely an issue we need to figure out in the libclc build, but it's broader than just the subgroup builtins here, so I'm not sure if it's worth doing a workaround just for this, I also ran into it in https://github.com/intel/llvm/pull/4223 a while back.

**Comment by Pennycook** [comment]
> This is definitely an issue we need to figure out in the libclc build, but it's broader than just the subgroup builtins here, so I'm not sure if it's worth doing a workaround just for this, I also ran into it in [intel/llvm#4223](https://github.com/intel/llvm/pull/4223) a while back.

Got it.  Thanks for the explanation.

FWIW, this sort of thing also impacts the CUDA backend.  The ability to generate floating-point atomics, for example (see  https://github.com/intel/llvm/pull/3276) depends on the SM architecture that libclc is being built for.  A general solution for multi-versioning and/or controlling the architecture used by libclc would be useful to multiple backends.

**Comment by jchlanda** [comment]
> To expand a bit on that `gfx906` and `gfx908` actually do support half as far as I understand it, the issue is that libspirv is currently built with `tahiti` as the target CPU, which means that clang rejects AMD built-ins using halfs, as `tahiti` doesn't support them.

Thanks @npmiller for the clarification, I'll update the comments to reflect that.

**Review by vladimirlaz — APPROVED** [review]

**Review by AlexeySachkov — APPROVED** [review]

**Pull request merged**
