### PR TITLE
[SYCL] Test indirect access memory tracking in the L0 plugin

### PR DESCRIPTION
**Pull request by againull**

### CODE REVIEW

**Comment by rdeodhar** [comment]
To improve readability I suggest
1. writing the accessors as: "accessor acc { b_d3_data, cgh, read_write };"
2. removing "cl::sycl::" throughout since you already have "using namespace sycl;"

But, what is the test checking exactly? Is indirect access tracking on by default?

**Comment by againull** [comment]
> To improve readability I suggest
> 
> 1. writing the accessors as: "accessor acc { b_d3_data, cgh, read_write };"
> 2. removing "cl::sycl::" throughout since you already have "using namespace sycl;"
> 
> But, what is the test checking exactly? Is indirect access tracking on by default?

Addressed comments and added description of the test.

**Review by smaslov-intel — APPROVED** [review]

**Comment by rdeodhar** [comment]
I ran the test on Gen9 with/without the env var on a recent build of intel/llvm.
Once, with the env var I got this error:
$ SYCL_PI_LEVEL_ZERO_TRACK_INDIRECT_ACCESS_MEMORY=1 ./a.out             
pass                                                                                                                                    
double free or corruption (out)                                    

There may still be a bug in the implementation, but I'm approving this PR for the test.

**Review by rdeodhar — APPROVED** [review]

**Comment by againull** [comment]
> I ran the test on Gen9 with/without the env var on a recent build of intel/llvm. Once, with the env var I got this error: $ SYCL_PI_LEVEL_ZERO_TRACK_INDIRECT_ACCESS_MEMORY=1 ./a.out pass double free or corruption (out)
> 
> There may still be a bug in the implementation, but I'm approving this PR for the test.

@rdeodhar  I can't reproduce this error with several thousand runs. Did you change the test or compiler somehow?

**Comment by rdeodhar** [comment]
I didn't change the test.
I ran it with an intel/llvm compiler as in PR 4891, which has just been merged. So effectively, with the latest intel/llvm compiler.

**Comment by againull** [comment]
> I didn't change the test. I ran it with an intel/llvm compiler as in PR 4891, which has just been merged. So effectively, with the latest intel/llvm compiler.

Still can't reproduce neither with build from PR 4891 nor the latest intel/llvm or nightly build.
Could you please create a tracker with detailed instructions.

**Comment by vladimirlaz** [comment]
is this PR still needed? Should it be merged?

**Comment by againull** [comment]
> is this PR still needed? Should it be merged?

It was waiting for gpu runtime version to be uplifted because old driver had an issue. GPU driver version was uplifted 4 days ago, so this can be merged now.

**Pull request merged**
