### PR TITLE
[SYCL] Enable release resource test on Linux

### PR DESCRIPTION
**Pull request by romanovvlad**

### CODE REVIEW

**Comment by romanovvlad** [comment]
Should work correctly after https://github.com/intel/llvm/pull/7727

**Review by sergey-semenov — APPROVED** [review]
What issues are we expecting on Windows?

**Comment by romanovvlad** [comment]
> What issues are we expecting on Windows?

We cannot safely release streams stored in `MDeferredMemObjRelease` as well as other objects we are currently leaking. https://github.com/intel/llvm/blob/sycl/sycl/source/detail/global_handler.cpp#L156

**Comment by romanovvlad** [comment]
The failed test is unrelated.

**Pull request merged**
