### PR TITLE
[ESIMD] Remove -vc-codegen option for ESIMD tests

### PR DESCRIPTION
**Pull request by DenisBakhvalov**

### CODE REVIEW

**Comment by DenisBakhvalov** [comment]
I will restart the jobs tomorrow after the nightly build with the required changes included.

**Review by kbobrovs — APPROVED** [review]
Cool, looks like this already works w/o -vc-codegen :)

**Review by vladimirlaz — CHANGES_REQUESTED** [review]
SYCL/ESIMD/vadd_1d.cpp should be also updated

**Comment by DenisBakhvalov** [comment]
> SYCL/ESIMD/vadd_1d.cpp should be also updated

This is done in https://github.com/intel/llvm-test-suite/pull/110

**Review by vladimirlaz — APPROVED** [review]

**Pull request merged**
