### PR TITLE
[SYCL] Replace SYCL_EXT_ONEAPI_MATRIX with SYCL_EXT_ONEAPI_MATRIX_VERSION

### PR DESCRIPTION
**Pull request by MrSidims**
Signed-off-by: Sidorov, Dmitry <dmitry.sidorov@intel.com>

### CODE REVIEW

**Review by dkhaldi — APPROVED** [review]
LGTM

**Comment by pvchupin** [comment]
Ping @cperkinsintel or @intel/llvm-reviewers-runtime for review.

**Comment by MrSidims** [comment]
For CUDA tests: was able to compile them manually, but execution requires something like A1000. But compilation should be good enough for testing, since it's a compilation macro change that switches different interfaces.

**Comment by MrSidims** [comment]
@cperkinsintel @intel/llvm-reviewers-runtime could you please check it? We need this patch and https://github.com/intel/llvm/pull/6957 to be merged ASAP

**Review by cperkinsintel — APPROVED** [review]
LGTM

**Pull request merged**
