### PR TITLE
[SYCL][ESIMD] Enable invoke_simd simd_mask test

### PR DESCRIPTION
**Pull request by sarnex**
Add tests for all valid simd_mask types and the boolean conversion to/from them.

Main PR: https://github.com/intel/llvm/pull/8524

### CODE REVIEW

**Comment by sarnex** [comment]
Failure is as expected as it required intel/llvm change

**Review by v-klochkov — APPROVED** [review]

**Comment by v-klochkov** [comment]
@sarnex - please take a look at this fail: http://llvm-ci2.intel.com:8080/job/SYCL_CI/job/intel/job/LLVM_Test_Suite_Associate_CI/536/display/redirect
[2023-03-06T21:07:16.159Z] Failed Tests (1):
[2023-03-06T21:07:16.159Z]   SYCL :: InvokeSimd/Spec/simd_mask.cpp

It fails at compile time due to tuple_for_each()

**Comment by sarnex** [comment]
@v-klochkov ah ok thanks, namespace problem

`use of undeclared identifier 'tuple_for_each'; did you mean 'sycl::detail::boost::mp11::tuple_for_each'?`

**Comment by v-klochkov** [comment]
@sarnex - Jenkins/llvm-test-suite failed catastrophically. Can you please do 'git merge' to this PR (and may-be the PR in ESIMD headers as well) to restart it?

**Comment by sarnex** [comment]
done, lets hope it works this time

**Comment by v-klochkov** [comment]
> /verify with [intel/llvm#8524](https://github.com/intel/llvm/pull/8524)

It seems sometimes (often?) such command is ignored. The first one was ignored this time.
Same command from me (1 minute ago) started the CI bot.

**Comment by sarnex** [comment]
> > /verify with [intel/llvm#8524](https://github.com/intel/llvm/pull/8524)
> 
> It seems sometimes (often?) such command is ignored. The first one was ignored this time. Same command from me (1 minute ago) started the CI bot.

weird, thanks.

**Comment by sarnex** [comment]
@v-klochkov I found with /verify with doeesn't work for me, I'm missing permissions, I'll try to get it fixed. Ping me offline if you're interested

**Pull request merged**
