### PR TITLE
[SYCL][ESIMD] Enable back smin/smax atomic tests

### PR DESCRIPTION
**Pull request by turinevgeny**

### CODE REVIEW

**Comment by turinevgeny** [comment]
I'll try to refresh old commented out lines and extend the test in subsequent patches.

**Comment by turinevgeny** [comment]
Complementary compiler PR: https://github.com/intel/llvm/pull/8527

**Review by v-klochkov — APPROVED** [review]

**Comment by v-klochkov** [comment]
The fails on pre-ci-linux and pre-ci-windows are expected because they do not use the updates in ESIMD headers/compiler.
The test passed with Jenkins/llvm-test-suite (i.e. with updates in ESIMD/compiler). Ready to merge.

**Pull request merged**
