### PR TITLE
[SYCL] Disambiguate atomic_ref references

### PR DESCRIPTION
**Pull request by ghost**
According to SYCL 2020, the atomic_ref type must become standard and be
placed into the sycl:: namespace. So, when two atomic_ref types are there,
the sycl::atomic_ref and sycl::ext::oneapi::atomic_ref ones, the reference
to atomic_ref will become ambiguous:

  SYCL/AtomicRef/sub.h(132,20): error: reference to 'atomic_ref' is ambiguous

To disambiguate the atomic_ref reference, the fully qualified name is used
in the tests.

Signed-off-by: Pavel Samolysov <pavel.samolysov@intel.com>

### CODE REVIEW

**Review by AGindinson — DISMISSED** [review]
LGTM.

**Comment by ghost** [comment]
I get the following error for llvm-test-suite as well as for intel/llvm:

```
slm_split_barrier.cpp(71,16): error: cannot initialize a parameter of type 'cl::sycl::ext::intel::experimental::esimd::fence_mask' with an rvalue of type 'cl::sycl::ext::intel::experimental::esimd::EsimdFenceMask'
[2021-11-01T14:27:39.220Z]   esimd::fence(ESIMD_GLOBAL_COHERENT_FENCE);
```

I'm sure, this PR doesn't touch any ESIMD-related code at all.

**Comment by Pennycook** [comment]
I don't understand why we're only testing the `sycl::ext::oneapi::` version of `atomic_ref`.  Shouldn't we be testing the version that we want people to use (i.e. `sycl::atomic_ref`)?

**Comment by ghost** [comment]
@Pennycook I'm going to get compilable tests to let the reviewers merge my PR in the compiler that adds `sycl::atomic_ref`. Then I'll add the tests for `sycl::atomic_ref` in llvm-test-suite.

**Review by steffenlarsen — DISMISSED** [review]
> I'm going to get compilable tests to let the reviewers merge my PR in the compiler that adds sycl::atomic_ref. Then I'll add the tests for sycl::atomic_ref in llvm-test-suite.

Sounds reasonable! LGTM.

**Comment by ghost** [comment]
The following code snippet fails in the `SYCL/DeprecatedFeatures/kernel_interop.cpp`:

```c++
  try {
    kernel Kernel(ClKernel, Context1);
  } catch (cl::sycl::invalid_parameter_error e) {
    Pass = true;
  }
  assert(Pass);
```

I see the control flow never comes in the catch block even though the exception type is changed to the modern `sycl::exception` as well as just the ellipsis `catch (...)`. I have no idea is it a change in the logic or an issue in the compiler.

**Review by AGindinson — DISMISSED** [review]

**Comment by ghost** [comment]
@steffenlarsen @Pennycook @AGindinson I've rebased the tests on the updated `intel` branch to solve problems with `pre-ci-linux` check. All the checks have passed. Could you review the PR again and merge it if it is possible? Thanks.

**Review by AGindinson — APPROVED** [review]

**Review by steffenlarsen — APPROVED** [review]

**Review by vladimirlaz — APPROVED** [review]

**Pull request merged**
