### PR TITLE
[ESIMD] Fixed vadd_1d test when compiler options are passed externally

### PR DESCRIPTION
**Pull request by DenisBakhvalov**

### CODE REVIEW

**Review by vladimirlaz — APPROVED** [review]
The failing test on CUDA is not connected to the change

**Comment by DenisBakhvalov** [comment]
@kbobrovs, ping.

**Comment by vladimirlaz** [comment]
@kbobrovs could you please review as the code owner?

**Review by kbobrovs — APPROVED** [review]

**Comment by kbobrovs** [comment]
Sorry for delay guys, approved.

**Pull request merged**
