### PR TITLE
Test the case where range is over allowed limit.

### PR DESCRIPTION
**Pull request by mmoadeli**
Provides a test for 
https://github.com/intel/llvm/pull/7968

### CODE REVIEW

**Comment by bader** [comment]
verify /[intel/llvm#7968](https://github.com/intel/llvm/pull/7968)

@mmoadeli, the command format is 

/verify with \<link to the PR\>

**Comment by abagusetty** [comment]
@mmoadeli Since this test works for HIP backend as well. May be: `REQUIRES: gpu, cuda, hip` ?

**Comment by bader** [comment]
> @mmoadeli Since this test works for HIP backend as well. May be: `REQUIRES: gpu, cuda, hip` ?

This will disable the test. There are no machines in CI where all three features are true at the same time.

**Comment by bader** [comment]
> /verify with [intel/llvm#7968](https://github.com/intel/llvm/pull/7968)

FYI: /verify with validates the change with OpenCL and Level Zero only. Tests requiring CUDA are not covered.

**Comment by abagusetty** [comment]
> 

Thanks @bader. Would `REQUIRES: opencl || level_zerp || cuda || hip` enables for appropriate combinations.

**Comment by bader** [comment]
> > 
> 
> Thanks @bader. Would `REQUIRES: opencl || level_zerp || cuda || hip` enables for appropriate combinations.

This looks like we expect the test to run with any back end, so it's better just remove `REQUIRES` at all.

**Comment by abagusetty** [comment]
> 

Thanks for the pointer.

**Comment by mmoadeli** [comment]
> /verify with [intel/llvm#7968](https://github.com/intel/llvm/pull/7968)

thanks @bader, @abagusetty, **REQUIRES**  is removed.

**Comment by bader** [comment]
@intel/llvm-reviewers-runtime, @bso-intel, ping.

**Review by bso-intel — APPROVED** [review]
LGTM

**Pull request merged**
