### PR TITLE
Add test for general bf16 isnan impl

### PR DESCRIPTION
**Pull request by jinge90**
Re-submit https://github.com/intel/llvm-test-suite/pull/1509 . Previously, this patch led to CUDA backend pre-commit failure, the root cause is a typo in patch, the new PR has fixed the typo and tested on CUDA backend.

### CODE REVIEW

**Comment by jinge90** [comment]
Hi, @bader and @aelovikov-intel 
I found the root cause of https://github.com/intel/llvm/issues/8040 and fixed it this PR.
Thanks very much.

**Comment by aelovikov-intel** [comment]
> I found the root cause of https://github.com/intel/llvm/issues/8040 and fixed it this PR

What was it?

**Comment by jinge90** [comment]
> > I found the root cause of [intel/llvm#8040](https://github.com/intel/llvm/issues/8040) and fixed it this PR
> 
> What was it?

The error code is set when function "check" returns true(https://github.com/intel/llvm-test-suite/blob/intel/SYCL/BFloat16/bfloat16_builtins.cpp#L41) which means "check" should return true when result and reference value doesn't math. The corrected version should be:
bool check(bool a, bool b) { return (a != b); }

Previously, the code is
bool check(bool a, bool b) { return (a == b); }

**Comment by GeorgeWeb** [comment]
Hi @jinge90, we were looking into this too and we're pleased to see this patch.

**Review by aelovikov-intel — APPROVED** [review]

**Comment by jinge90** [comment]
Hi, @intel/dpcpp-tools-reviewers 
Could you help review this PR?
Thanks very much.

**Comment by GeorgeWeb** [comment]
Hi @intel/dpcpp-tools-reviewers / @AlexeySachkov :wave:. Would it be possible to review and merge this?
Thank youi!

**Review by sarnex — APPROVED** [review]
No merge permission though, sorry :)

**Pull request merged**
