### PR TITLE
[SYCL] Update tests to use local_accessor

### PR DESCRIPTION
**Pull request by AidanBeltonS**
This PR updates tests that use `target::local` to local_accessor. In all cases the change should not functionally change the test. The goal is to move from the deprecated `target::local` accessor to `local_accessor`.

Depends on: https://github.com/intel/llvm/pull/6341

### CODE REVIEW

**Review by steffenlarsen — DISMISSED** [review]

**Comment by steffenlarsen** [comment]
@AidanBeltonS - Could you please resolve conflicts?

**Comment by steffenlarsen** [comment]
Failures are likely due prebuilt intel/llvm being used from before the changes were merged. Should be resolved by rerunning the tests later.

**Comment by AidanBeltonS** [comment]
> Failures are likely due prebuilt intel/llvm being used from before the changes were merged. Should be resolved by rerunning the tests later.

Would it be possible to rerun the tests now and see if they pass?

**Comment by steffenlarsen** [comment]
Reran tests. Looks like there are some potentially related failures in pre-ci-linux. pre-ci-windows currently has a series of failures we are working on fixing so please disregard that for now.

**Comment by AidanBeltonS** [comment]
> Reran tests. Looks like there are some potentially related failures in pre-ci-linux. pre-ci-windows currently has a series of failures we are working on fixing so please disregard that for now.

I have fixed the linux ci issues. Windows is still failing I think due to unrelated problems

**Review by steffenlarsen — APPROVED** [review]

**Pull request merged**
