### PR TITLE
[SYCL] Test info::device::local_mem_type

### PR DESCRIPTION
**Pull request by smaslov-intel**

### CODE REVIEW

**Review by steffenlarsen — APPROVED** [review]
Simple but effective! LGTM!

**Comment by steffenlarsen** [comment]
Failure in USM/copy2d.cpp is unrelated. I am investigating the cause.

**Comment by bashbaug** [comment]
Note, I don't think this test is correct in all cases because there is no guarantee that the default device will have local memory (consider a system with only CPU devices, for example).

**Comment by steffenlarsen** [comment]
The test is only run on GPU at the moment, but we could explicitly write out that requirement if you think that would be better?

**Pull request merged**
