### PR TITLE
Set the feature macro to use the non-use matrix API

### PR DESCRIPTION
**Pull request by dkhaldi**
By default, a new API that has an extra "use" argument will be used.
So for the other tests that use the old API, the macro will have to be explicitly set

### CODE REVIEW

**Review by aelovikov-intel — APPROVED** [review]
Please add a link to the functional change in this PR's conversation.

**Review by yubingex007-a11y — APPROVED** [review]
LGTM

**Comment by dkhaldi** [comment]
@aelovikov-intel, the fails are not related to this change?
Can we merge this PR?

**Comment by aelovikov-intel** [comment]
> @aelovikov-intel, the fails are not related to this change? Can we merge this PR?

I don't have commit rights. @intel/llvm-gatekeepers are able to merge PRs.

**Comment by pvchupin** [comment]
Fails are probably related to https://github.com/intel/llvm-test-suite/pull/1289

**Comment by pvchupin** [comment]
By default, a new API that has an extra "use" argument will be used.
So for the other tests that use the old API, the macro will have to be explicitly set

**Pull request merged**
