### PR TITLE
[SYCL][ESIMD] improved kmean

### PR DESCRIPTION
**Pull request by cmc-rep**
We changed the data-layout to use block-read to get better performance on GPU.
So kernel is basically rewritten. also changed the input to use csv file

Signed-off-by: Gang Y Chen <gang.y.chen@intel.com>

### CODE REVIEW

**Comment by cmc-rep** [comment]
@DenisBakhvalov, please review and merge

**Comment by DenisBakhvalov** [comment]
@cmc-rep, what kind of improvement you've made in this patch? Is it just refactoring or it is performance improvement? Please update the description.
It is quite hard to review such a massive change. Could you please next time split your patches into smaller parts? It would be really helpful.

**Comment by cmc-rep** [comment]
We changed the data-layout to use block-read in order to get better performance on GPU.  So kernel is basically rewritten.  It is not possible to split into small patch.

**Comment by DenisBakhvalov** [comment]
> We changed the data-layout to use block-read in order to get better performance on GPU. So kernel is basically rewritten. It is not possible to split into small patch.

Thanks, could you please update the description of the PR?

**Comment by cmc-rep** [comment]
updated

**Review by DenisBakhvalov — APPROVED** [review]

**Comment by cmc-rep** [comment]
@vladimirlaz, please merge this.

**Pull request merged**
