### PR TITLE
[SYCL] Add tests for SYCL_RT_WARNING_LEVEL

### PR DESCRIPTION
**Pull request by alexbatashev**

### CODE REVIEW

**Comment by bader** [comment]
@alexbatashev, are you going to finish this PR? It blocks https://github.com/intel/llvm/pull/5319.

**Comment by alexbatashev** [comment]
This test depends on https://github.com/intel/llvm/pull/5319

**Comment by bader** [comment]
I know that. Why is this PR still draft? If you are going to change the test, I won't merge https://github.com/intel/llvm/pull/5319. I want to have final versions for both PRs.

**Review by steffenlarsen — APPROVED** [review]
LGTM!

**Pull request merged**
