### PR TITLE
Add tests for trivial fp16 util functions.

### PR DESCRIPTION
**Pull request by jinge90**
Signed-off-by: jinge90 <ge.jin@intel.com>

### CODE REVIEW

**Comment by jinge90** [comment]
This PR is test for https://github.com/intel/llvm/pull/6691

**Review by cperkinsintel — APPROVED** [review]
LGTM

**Comment by jinge90** [comment]
Hi, @cperkinsintel 
I updated the PR to add check for platform without fp16 support, could you help review again?
Thanks very much.

**Review by cperkinsintel — APPROVED** [review]

**Comment by jinge90** [comment]
One test failed on Windows:
 SYCL :: KernelAndProgram/kernel-bundle-merge-options-env.cpp
This failure should not be related to this PR.

Hi, @pvchupin 
Could you help merge this PR?

Thanks very much.

**Pull request merged**
