### PR TITLE
[SYCL] Remove deprecated buffer interop case after removal

### PR DESCRIPTION
**Pull request by steffenlarsen**
Removed the deprecated SYCL 1.2.1 interop constructor for buffer. This causes buffer_interop.cpp to fail in a selection of cases. This commit removes the failing cases.

### CODE REVIEW

**Review by aelovikov-intel — APPROVED** [review]
I assume SYCL2020 interop feature had its own tests and hence these can simply be removed.

**Comment by steffenlarsen** [comment]
> I assume SYCL2020 interop feature had its own tests and hence these can simply be removed.

SYCL/Basic/interop/construction_ocl.cpp, SYCL/Plugin/interop-opencl.cpp, and SYCL/Plugin/interop-level-zero-buffer.cpp should cover `sycl::make_buffer` for OpenCL and L0. I would expect CTS to also cover the OpenCL side.

**Comment by romanovvlad** [comment]
I think we will remove rest of the test together with the program class.

**Comment by romanovvlad** [comment]
The run lines could be updated to:

```
// REQUIRES: opencl
// RUN: %clangxx -fsycl -fsycl-targets=%sycl_triple %s -D__SYCL_INTERNAL_API -o %t.out
```

**Pull request merged**
