### PR TITLE
add gpu-intel-dg2 support to available_features.

### PR DESCRIPTION
**Pull request by myler**

### CODE REVIEW

**Comment by myler** [comment]
We already have two tests require this feature:
```
ESIMD/dpas/dpas_test1.cpp:8:// REQUIRES: gpu-intel-dg2
ESIMD/dpas/dpasw_test.cpp:8:// REQUIRES: gpu-intel-dg2
```

**Comment by cperkinsintel** [comment]
@myler  - the README.md should probably be updated as well.

Do we have infrastructure with DG2 set up?

**Comment by myler** [comment]
> @myler - the README.md should probably be updated as well.
> 
> Do we have infrastructure with DG2 set up?

Our internal infrastructure has DG2 setup.

**Review by cperkinsintel — APPROVED** [review]
LGTM

**Comment by myler** [comment]
Hi @cperkinsintel 
The merging is still blocked, do you know how can I rerun the `clang-format-check / build (pull_request) `  ?

**Comment by steffenlarsen** [comment]
clang-format failure was unrelated to this and has been fixed separately. Rerun does not reflect the fix so this is merged without format approval, though there is no reason to believe this would have failed clang-format.

**Pull request merged**
