### PR TITLE
[SYCL] Remove XFAIL for AMD from group collectives related tests

### PR DESCRIPTION
**Pull request by t4c1**
Remove XFAIL for AMD from group collectives related tests. Tests changes in: https://github.com/intel/llvm/pull/5202

### CODE REVIEW

**Review by AlexeySachkov — DISMISSED** [review]

**Review by Pennycook — DISMISSED** [review]

**Comment by bader** [comment]
@t4c1, please, resolve merge conflicts.

**Review by againull — APPROVED** [review]

**Comment by bader** [comment]
@t4c1, SYCL/SubGroup/broadcast* tests don't work - https://github.com/intel/llvm/runs/4808006579?check_suite_focus=true

**Comment by t4c1** [comment]
These tests pass for me :/ Given they are failing on CI I can add back the XFAIL.

**Comment by bader** [comment]
Please, do. These tests fail in all recent pre-commit checks.
https://github.com/intel/llvm/actions/workflows/sycl_precommit.yml

**Pull request merged**
