### PR TITLE
[SYCL][CUDA] CXX std lib funcs for CUDA backend

### PR DESCRIPTION
**Pull request by hdelan**
Relating to PR https://github.com/intel/llvm/pull/6482

### CODE REVIEW

**Comment by steffenlarsen** [comment]
@hdelan - Could you please add a merge commit to rerun testing?

**Comment by hdelan** [comment]
Yep done

**Review by steffenlarsen — APPROVED** [review]
LGTM!

**Comment by steffenlarsen** [comment]
Windows failures are known and are unrelated.

**Pull request merged**
