### PR TITLE
[SYCL][CUDA] Enable tests for generic atomics

### LINKED ISSUE #8807: [CUDA] Enable tests in AtomicRef for CUDA after adding support for generic address space in DPC++
Currently the tests in `AtomicRef` for the generic address space are separated in different `*_generic.cpp` files just to let us disable them on CUDA. After support for the generic address space is added to the CUDA backend, the tests should be enabled and can be merged into the .cpp files for the tests with the global address space.

See also: https://github.com/intel/llvm/issues/5215

### PR DESCRIPTION
**Pull request by t4c1**
Enables tests for generic atomics for CUDA backend.

Tests https://github.com/intel/llvm/pull/5849.

Closes https://github.com/intel/llvm/issues/8807.

### CODE REVIEW

**Comment by denis-kabanov** [comment]
@t4c1, I think these XFAILs should not be removed due to [comment](https://github.com/intel/llvm/pull/5430#issuecomment-1073762429), can you sync [commit](https://github.com/intel/llvm/pull/5849/commits/0c113e07b3ce102b320c6bedecbfaa28e952307e) with syclos?

**Comment by steffenlarsen** [comment]
@t4c1 - Could you please push a rebase or a merge commit so retrigger testing?

**Comment by t4c1** [comment]
I would not expect this to be merged anyway, as the PR this is testing hit on some remangler issues on Windows. The last set of tests only passed because tests were somehow not run on Windows.

**Comment by steffenlarsen** [comment]
> I would not expect this to be merged anyway, as the PR this is testing hit on some remangler issues on Windows. The last set of tests only passed because tests were somehow not run on Windows.

In that case, should this be moved to draft?

**Comment by jchlanda** [comment]
This can be closed now that https://github.com/intel/llvm-test-suite/pull/1446 is in, right @t4c1 ?

**Comment by t4c1** [comment]
Yes, I think so.

**Pull request closed without merging**
