### PR TITLE
[SYCL] updating device selectors

### PR DESCRIPTION
**Pull request by cperkinsintel**
The SYCL 1.2.1 style device_selector subclasses are now deprecated. In this PR we are updating the tests to use the newer SYCL 2020 ones.  This avoids encountering all the "deprecation" warnings when running verbose tests.

The deprecation warnings are being added in https://github.com/intel/llvm/pull/6599  .

Signed-off-by: Chris Perkins <chris.perkins@intel.com>

### CODE REVIEW

**Review by AlexeySachkov — DISMISSED** [review]

**Review by v-klochkov — COMMENTED** [review]
Looks good in general, but there is 1 or 2 test fails caused by this PR.
In particular program_link.cpp fail (syntax error) is definitely caused by this change.

**Comment by cperkinsintel** [comment]
will  have a failure in `event_creation_oepncl.cpp` until https://github.com/intel/llvm-test-suite/pull/1161  is merged.

**Review by v-klochkov — DISMISSED** [review]

**Review by AlexeySachkov — DISMISSED** [review]

**Review by v-klochkov — DISMISSED** [review]

**Review by v-klochkov — APPROVED** [review]

**Comment by cperkinsintel** [comment]
ping to reviewers. I had to set this aside to work on something else, but now it has been deconflicted again and is passing all tests. Would love to get this in and merged. 

This PR mostly just replaces instances of `gpu_selector{}` (et al) with `gpu_selector_v` to avoid the deprecation warnings that the compiler is outputting now on those old style selectors.

**Review by smaslov-intel — APPROVED** [review]
LGTM

**Pull request merged**
